/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Simulation Protocol Definition — Scenarios, Synthetic Worlds, Agents, Metrics
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/simulation.proto

package simulation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SimulationAgent represents an agent within a simulation scenario.
type SimulationAgent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Role         string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Capabilities []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	State        string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Constraints  []string               `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationAgent) Reset() {
	*x = SimulationAgent{}
	mi := &file_proto_v1_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationAgent) ProtoMessage() {}

func (x *SimulationAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationAgent.ProtoReflect.Descriptor instead.
func (*SimulationAgent) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimulationAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SimulationAgent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SimulationAgent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SimulationAgent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SimulationAgent) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SimulationAgent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SimulationAgent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationAgent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SimulationAgent) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SimulationAgent) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SimulationAgent) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ScenarioMetrics captures quantitative metrics for a simulation run.
type ScenarioMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MetricsId            string                 `protobuf:"bytes,1,opt,name=metrics_id,json=metricsId,proto3" json:"metrics_id,omitempty"`
	Latency              float64                `protobuf:"fixed64,2,opt,name=latency,proto3" json:"latency,omitempty"`
	DeterminismScore     float64                `protobuf:"fixed64,3,opt,name=determinism_score,json=determinismScore,proto3" json:"determinism_score,omitempty"`
	ReproducibilityScore float64                `protobuf:"fixed64,4,opt,name=reproducibility_score,json=reproducibilityScore,proto3" json:"reproducibility_score,omitempty"`
	Coverage             float64                `protobuf:"fixed64,5,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Stability            float64                `protobuf:"fixed64,6,opt,name=stability,proto3" json:"stability,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScenarioMetrics) Reset() {
	*x = ScenarioMetrics{}
	mi := &file_proto_v1_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioMetrics) ProtoMessage() {}

func (x *ScenarioMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioMetrics.ProtoReflect.Descriptor instead.
func (*ScenarioMetrics) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioMetrics) GetMetricsId() string {
	if x != nil {
		return x.MetricsId
	}
	return ""
}

func (x *ScenarioMetrics) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *ScenarioMetrics) GetDeterminismScore() float64 {
	if x != nil {
		return x.DeterminismScore
	}
	return 0
}

func (x *ScenarioMetrics) GetReproducibilityScore() float64 {
	if x != nil {
		return x.ReproducibilityScore
	}
	return 0
}

func (x *ScenarioMetrics) GetCoverage() float64 {
	if x != nil {
		return x.Coverage
	}
	return 0
}

func (x *ScenarioMetrics) GetStability() float64 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *ScenarioMetrics) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ScenarioMetrics) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScenarioMetrics) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ScenarioMetrics) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ScenarioMetrics) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ScenarioMetrics) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SimulationScenario defines a complete simulation test scenario.
type SimulationScenario struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId       string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Seed             string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	WorldConfig      string                 `protobuf:"bytes,3,opt,name=world_config,json=worldConfig,proto3" json:"world_config,omitempty"`
	AgentSet         []*SimulationAgent     `protobuf:"bytes,4,rep,name=agent_set,json=agentSet,proto3" json:"agent_set,omitempty"`
	ExpectedOutcomes []string               `protobuf:"bytes,5,rep,name=expected_outcomes,json=expectedOutcomes,proto3" json:"expected_outcomes,omitempty"`
	ReplaySequence   uint64                 `protobuf:"varint,6,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationScenario) Reset() {
	*x = SimulationScenario{}
	mi := &file_proto_v1_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationScenario) ProtoMessage() {}

func (x *SimulationScenario) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationScenario.ProtoReflect.Descriptor instead.
func (*SimulationScenario) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationScenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SimulationScenario) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *SimulationScenario) GetWorldConfig() string {
	if x != nil {
		return x.WorldConfig
	}
	return ""
}

func (x *SimulationScenario) GetAgentSet() []*SimulationAgent {
	if x != nil {
		return x.AgentSet
	}
	return nil
}

func (x *SimulationScenario) GetExpectedOutcomes() []string {
	if x != nil {
		return x.ExpectedOutcomes
	}
	return nil
}

func (x *SimulationScenario) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SimulationScenario) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SimulationScenario) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationScenario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SimulationScenario) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SimulationScenario) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SyntheticWorld defines the world configuration for a simulation.
type SyntheticWorld struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorldId           string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Topology          string                 `protobuf:"bytes,2,opt,name=topology,proto3" json:"topology,omitempty"`
	Rules             string                 `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	InitialState      string                 `protobuf:"bytes,4,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	DeterministicSeed string                 `protobuf:"bytes,5,opt,name=deterministic_seed,json=deterministicSeed,proto3" json:"deterministic_seed,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyntheticWorld) Reset() {
	*x = SyntheticWorld{}
	mi := &file_proto_v1_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticWorld) ProtoMessage() {}

func (x *SyntheticWorld) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticWorld.ProtoReflect.Descriptor instead.
func (*SyntheticWorld) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{3}
}

func (x *SyntheticWorld) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *SyntheticWorld) GetTopology() string {
	if x != nil {
		return x.Topology
	}
	return ""
}

func (x *SyntheticWorld) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *SyntheticWorld) GetInitialState() string {
	if x != nil {
		return x.InitialState
	}
	return ""
}

func (x *SyntheticWorld) GetDeterministicSeed() string {
	if x != nil {
		return x.DeterministicSeed
	}
	return ""
}

func (x *SyntheticWorld) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SyntheticWorld) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SyntheticWorld) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SyntheticWorld) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SyntheticWorld) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SyntheticWorld) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SimulationEvent records a single step in a simulation execution.
type SimulationEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SimEventId string                 `protobuf:"bytes,1,opt,name=sim_event_id,json=simEventId,proto3" json:"sim_event_id,omitempty"`
	ScenarioId string                 `protobuf:"bytes,2,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Step       uint64                 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Actor      string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	StateDelta string                 `protobuf:"bytes,5,opt,name=state_delta,json=stateDelta,proto3" json:"state_delta,omitempty"`
	Checksum   string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationEvent) Reset() {
	*x = SimulationEvent{}
	mi := &file_proto_v1_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent) ProtoMessage() {}

func (x *SimulationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent.ProtoReflect.Descriptor instead.
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{4}
}

func (x *SimulationEvent) GetSimEventId() string {
	if x != nil {
		return x.SimEventId
	}
	return ""
}

func (x *SimulationEvent) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SimulationEvent) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *SimulationEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *SimulationEvent) GetStateDelta() string {
	if x != nil {
		return x.StateDelta
	}
	return ""
}

func (x *SimulationEvent) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *SimulationEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SimulationEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SimulationEvent) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SimulationEvent) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SimulationEvent) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SimulationResult records the outcome of a simulation scenario execution.
type SimulationResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ResultId     string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	ScenarioId   string                 `protobuf:"bytes,2,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Outcome      string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Divergence   string                 `protobuf:"bytes,4,opt,name=divergence,proto3" json:"divergence,omitempty"`
	Metrics      *ScenarioMetrics       `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ReplayMarker uint64                 `protobuf:"varint,6,opt,name=replay_marker,json=replayMarker,proto3" json:"replay_marker,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationResult) Reset() {
	*x = SimulationResult{}
	mi := &file_proto_v1_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResult) ProtoMessage() {}

func (x *SimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResult.ProtoReflect.Descriptor instead.
func (*SimulationResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_simulation_proto_rawDescGZIP(), []int{5}
}

func (x *SimulationResult) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *SimulationResult) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *SimulationResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *SimulationResult) GetDivergence() string {
	if x != nil {
		return x.Divergence
	}
	return ""
}

func (x *SimulationResult) GetMetrics() *ScenarioMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SimulationResult) GetReplayMarker() uint64 {
	if x != nil {
		return x.ReplayMarker
	}
	return 0
}

func (x *SimulationResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SimulationResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SimulationResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SimulationResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SimulationResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SimulationResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_simulation_proto protoreflect.FileDescriptor

const file_proto_v1_simulation_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v1/simulation.proto\x12\x15phoenix.simulation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n" +
	"\x0fSimulationAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12 \n" +
	"\vconstraints\x18\x05 \x03(\tR\vconstraints\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xf6\x03\n" +
	"\x0fScenarioMetrics\x12\x1d\n" +
	"\n" +
	"metrics_id\x18\x01 \x01(\tR\tmetricsId\x12\x18\n" +
	"\alatency\x18\x02 \x01(\x01R\alatency\x12+\n" +
	"\x11determinism_score\x18\x03 \x01(\x01R\x10determinismScore\x123\n" +
	"\x15reproducibility_score\x18\x04 \x01(\x01R\x14reproducibilityScore\x12\x1a\n" +
	"\bcoverage\x18\x05 \x01(\x01R\bcoverage\x12\x1c\n" +
	"\tstability\x18\x06 \x01(\x01R\tstability\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xee\x03\n" +
	"\x12SimulationScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12!\n" +
	"\fworld_config\x18\x03 \x01(\tR\vworldConfig\x12C\n" +
	"\tagent_set\x18\x04 \x03(\v2&.phoenix.simulation.v1.SimulationAgentR\bagentSet\x12+\n" +
	"\x11expected_outcomes\x18\x05 \x03(\tR\x10expectedOutcomes\x12'\n" +
	"\x0freplay_sequence\x18\x06 \x01(\x04R\x0ereplaySequence\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xc1\x03\n" +
	"\x0eSyntheticWorld\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x1a\n" +
	"\btopology\x18\x02 \x01(\tR\btopology\x12\x14\n" +
	"\x05rules\x18\x03 \x01(\tR\x05rules\x12#\n" +
	"\rinitial_state\x18\x04 \x01(\tR\finitialState\x12-\n" +
	"\x12deterministic_seed\x18\x05 \x01(\tR\x11deterministicSeed\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xcb\x03\n" +
	"\x0fSimulationEvent\x12 \n" +
	"\fsim_event_id\x18\x01 \x01(\tR\n" +
	"simEventId\x12\x1f\n" +
	"\vscenario_id\x18\x02 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x04R\x04step\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x1f\n" +
	"\vstate_delta\x18\x05 \x01(\tR\n" +
	"stateDelta\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\x81\x04\n" +
	"\x10SimulationResult\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x1f\n" +
	"\vscenario_id\x18\x02 \x01(\tR\n" +
	"scenarioId\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x1e\n" +
	"\n" +
	"divergence\x18\x04 \x01(\tR\n" +
	"divergence\x12@\n" +
	"\ametrics\x18\x05 \x01(\v2&.phoenix.simulation.v1.ScenarioMetricsR\ametrics\x12#\n" +
	"\rreplay_marker\x18\x06 \x01(\x04R\freplayMarker\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashB:Z8github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/simulationb\x06proto3"

var (
	file_proto_v1_simulation_proto_rawDescOnce sync.Once
	file_proto_v1_simulation_proto_rawDescData []byte
)

func file_proto_v1_simulation_proto_rawDescGZIP() []byte {
	file_proto_v1_simulation_proto_rawDescOnce.Do(func() {
		file_proto_v1_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_simulation_proto_rawDesc), len(file_proto_v1_simulation_proto_rawDesc)))
	})
	return file_proto_v1_simulation_proto_rawDescData
}

var file_proto_v1_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_simulation_proto_goTypes = []any{
	(*SimulationAgent)(nil),       // 0: phoenix.simulation.v1.SimulationAgent
	(*ScenarioMetrics)(nil),       // 1: phoenix.simulation.v1.ScenarioMetrics
	(*SimulationScenario)(nil),    // 2: phoenix.simulation.v1.SimulationScenario
	(*SyntheticWorld)(nil),        // 3: phoenix.simulation.v1.SyntheticWorld
	(*SimulationEvent)(nil),       // 4: phoenix.simulation.v1.SimulationEvent
	(*SimulationResult)(nil),      // 5: phoenix.simulation.v1.SimulationResult
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_simulation_proto_depIdxs = []int32{
	6,  // 0: phoenix.simulation.v1.SimulationAgent.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.simulation.v1.SimulationAgent.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.simulation.v1.ScenarioMetrics.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.simulation.v1.ScenarioMetrics.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: phoenix.simulation.v1.SimulationScenario.agent_set:type_name -> phoenix.simulation.v1.SimulationAgent
	6,  // 5: phoenix.simulation.v1.SimulationScenario.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: phoenix.simulation.v1.SimulationScenario.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: phoenix.simulation.v1.SyntheticWorld.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.simulation.v1.SyntheticWorld.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.simulation.v1.SimulationEvent.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.simulation.v1.SimulationEvent.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: phoenix.simulation.v1.SimulationResult.metrics:type_name -> phoenix.simulation.v1.ScenarioMetrics
	6,  // 12: phoenix.simulation.v1.SimulationResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 13: phoenix.simulation.v1.SimulationResult.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_simulation_proto_init() }
func file_proto_v1_simulation_proto_init() {
	if File_proto_v1_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_simulation_proto_rawDesc), len(file_proto_v1_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_simulation_proto_goTypes,
		DependencyIndexes: file_proto_v1_simulation_proto_depIdxs,
		MessageInfos:      file_proto_v1_simulation_proto_msgTypes,
	}.Build()
	File_proto_v1_simulation_proto = out.File
	file_proto_v1_simulation_proto_goTypes = nil
	file_proto_v1_simulation_proto_depIdxs = nil
}
