FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache libbpf iproute2

COPY core/Phoenix.Terminus/bin/phoenixd /app/phoenixd
RUN chmod +x /app/phoenixd
RUN mkdir -p /app/PhoenixKernel/src/
COPY core/Phoenix.Nucleus/PhoenixKernel/src/phoenix_exec.o /app/PhoenixKernel/src/

# UDP for Beacon discovery
EXPOSE 9999/udp
# TCP for Game Server / API
EXPOSE 8080

ENTRYPOINT ["./phoenixd"]
