// PheonixCore — Canonical Contract System
// Ledger Protocol Definition — Append-Only Evidence Ledger
// ALL repos depend on PheonixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvidenceRecord represents a single piece of cryptographic evidence
// recorded in the append-only ledger.
type EvidenceRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId      string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	SourceRef       string                 `protobuf:"bytes,2,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	EvidenceHash    string                 `protobuf:"bytes,3,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	SourceRepo      string                 `protobuf:"bytes,4,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	SourceComponent string                 `protobuf:"bytes,5,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TrustScore      float64                `protobuf:"fixed64,7,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	LineageRef      string                 `protobuf:"bytes,9,opt,name=lineage_ref,json=lineageRef,proto3" json:"lineage_ref,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,10,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,13,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,14,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceRecord) Reset() {
	*x = EvidenceRecord{}
	mi := &file_proto_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceRecord) ProtoMessage() {}

func (x *EvidenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceRecord.ProtoReflect.Descriptor instead.
func (*EvidenceRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *EvidenceRecord) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *EvidenceRecord) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *EvidenceRecord) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *EvidenceRecord) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EvidenceRecord) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *EvidenceRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EvidenceRecord) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *EvidenceRecord) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EvidenceRecord) GetLineageRef() string {
	if x != nil {
		return x.LineageRef
	}
	return ""
}

func (x *EvidenceRecord) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EvidenceRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EvidenceRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EvidenceRecord) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EvidenceRecord) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// TransitionProof provides cryptographic proof that a state transition
// was valid according to the FSM contract.
type TransitionProof struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ProofId      string                 `protobuf:"bytes,1,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	FromState    string                 `protobuf:"bytes,2,opt,name=from_state,json=fromState,proto3" json:"from_state,omitempty"`
	ToState      string                 `protobuf:"bytes,3,opt,name=to_state,json=toState,proto3" json:"to_state,omitempty"`
	PreimageHash string                 `protobuf:"bytes,4,opt,name=preimage_hash,json=preimageHash,proto3" json:"preimage_hash,omitempty"`
	ValidatorSet []string               `protobuf:"bytes,5,rep,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	ReplayMarker uint64                 `protobuf:"varint,6,opt,name=replay_marker,json=replayMarker,proto3" json:"replay_marker,omitempty"`
	Signature    string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransitionProof) Reset() {
	*x = TransitionProof{}
	mi := &file_proto_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionProof) ProtoMessage() {}

func (x *TransitionProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionProof.ProtoReflect.Descriptor instead.
func (*TransitionProof) Descriptor() ([]byte, []int) {
	return file_proto_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *TransitionProof) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

func (x *TransitionProof) GetFromState() string {
	if x != nil {
		return x.FromState
	}
	return ""
}

func (x *TransitionProof) GetToState() string {
	if x != nil {
		return x.ToState
	}
	return ""
}

func (x *TransitionProof) GetPreimageHash() string {
	if x != nil {
		return x.PreimageHash
	}
	return ""
}

func (x *TransitionProof) GetValidatorSet() []string {
	if x != nil {
		return x.ValidatorSet
	}
	return nil
}

func (x *TransitionProof) GetReplayMarker() uint64 {
	if x != nil {
		return x.ReplayMarker
	}
	return 0
}

func (x *TransitionProof) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TransitionProof) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TransitionProof) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransitionProof) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TransitionProof) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *TransitionProof) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *TransitionProof) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// LedgerEntry is a single append-only entry in the evidence ledger.
// Once written, a LedgerEntry MUST NEVER be modified or deleted.
type LedgerEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntryId         string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	EvidenceRecord  *EvidenceRecord        `protobuf:"bytes,2,opt,name=evidence_record,json=evidenceRecord,proto3" json:"evidence_record,omitempty"`
	StateBefore     string                 `protobuf:"bytes,3,opt,name=state_before,json=stateBefore,proto3" json:"state_before,omitempty"`
	StateAfter      string                 `protobuf:"bytes,4,opt,name=state_after,json=stateAfter,proto3" json:"state_after,omitempty"`
	TransitionProof *TransitionProof       `protobuf:"bytes,5,opt,name=transition_proof,json=transitionProof,proto3" json:"transition_proof,omitempty"`
	ReplaySequence  uint64                 `protobuf:"varint,6,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	CheckpointId    string                 `protobuf:"bytes,7,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,12,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_proto_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *LedgerEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *LedgerEntry) GetEvidenceRecord() *EvidenceRecord {
	if x != nil {
		return x.EvidenceRecord
	}
	return nil
}

func (x *LedgerEntry) GetStateBefore() string {
	if x != nil {
		return x.StateBefore
	}
	return ""
}

func (x *LedgerEntry) GetStateAfter() string {
	if x != nil {
		return x.StateAfter
	}
	return ""
}

func (x *LedgerEntry) GetTransitionProof() *TransitionProof {
	if x != nil {
		return x.TransitionProof
	}
	return nil
}

func (x *LedgerEntry) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *LedgerEntry) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *LedgerEntry) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *LedgerEntry) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LedgerEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LedgerEntry) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *LedgerEntry) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// VerificationResult records the outcome of verifying a ledger entry
// for integrity, tamper-detection, and chain consistency.
type VerificationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VerificationId string                 `protobuf:"bytes,1,opt,name=verification_id,json=verificationId,proto3" json:"verification_id,omitempty"`
	LedgerEntryId  string                 `protobuf:"bytes,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TamperDetected bool                   `protobuf:"varint,4,opt,name=tamper_detected,json=tamperDetected,proto3" json:"tamper_detected,omitempty"`
	Checksum       string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Verifier       string                 `protobuf:"bytes,6,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Signature      string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationResult) Reset() {
	*x = VerificationResult{}
	mi := &file_proto_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResult) ProtoMessage() {}

func (x *VerificationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResult.ProtoReflect.Descriptor instead.
func (*VerificationResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationResult) GetVerificationId() string {
	if x != nil {
		return x.VerificationId
	}
	return ""
}

func (x *VerificationResult) GetLedgerEntryId() string {
	if x != nil {
		return x.LedgerEntryId
	}
	return ""
}

func (x *VerificationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerificationResult) GetTamperDetected() bool {
	if x != nil {
		return x.TamperDetected
	}
	return false
}

func (x *VerificationResult) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *VerificationResult) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

func (x *VerificationResult) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerificationResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *VerificationResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VerificationResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VerificationResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *VerificationResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *VerificationResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ChainCheckpoint represents a periodic checkpoint of the ledger chain
// for fast verification and recovery.
type ChainCheckpoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId    string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	LastEntryId     string                 `protobuf:"bytes,2,opt,name=last_entry_id,json=lastEntryId,proto3" json:"last_entry_id,omitempty"`
	CumulativeHash  string                 `protobuf:"bytes,3,opt,name=cumulative_hash,json=cumulativeHash,proto3" json:"cumulative_hash,omitempty"`
	ValidatorQuorum []string               `protobuf:"bytes,4,rep,name=validator_quorum,json=validatorQuorum,proto3" json:"validator_quorum,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature       string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainCheckpoint) Reset() {
	*x = ChainCheckpoint{}
	mi := &file_proto_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainCheckpoint) ProtoMessage() {}

func (x *ChainCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainCheckpoint.ProtoReflect.Descriptor instead.
func (*ChainCheckpoint) Descriptor() ([]byte, []int) {
	return file_proto_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ChainCheckpoint) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *ChainCheckpoint) GetLastEntryId() string {
	if x != nil {
		return x.LastEntryId
	}
	return ""
}

func (x *ChainCheckpoint) GetCumulativeHash() string {
	if x != nil {
		return x.CumulativeHash
	}
	return ""
}

func (x *ChainCheckpoint) GetValidatorQuorum() []string {
	if x != nil {
		return x.ValidatorQuorum
	}
	return nil
}

func (x *ChainCheckpoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChainCheckpoint) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ChainCheckpoint) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ChainCheckpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChainCheckpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChainCheckpoint) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ChainCheckpoint) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ChainCheckpoint) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_ledger_proto protoreflect.FileDescriptor

const file_proto_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/ledger.proto\x12\x11phoenix.ledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x04\n" +
	"\x0eEvidenceRecord\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x02 \x01(\tR\tsourceRef\x12#\n" +
	"\revidence_hash\x18\x03 \x01(\tR\fevidenceHash\x12\x1f\n" +
	"\vsource_repo\x18\x04 \x01(\tR\n" +
	"sourceRepo\x12)\n" +
	"\x10source_component\x18\x05 \x01(\tR\x0fsourceComponent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vtrust_score\x18\a \x01(\x01R\n" +
	"trustScore\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x1f\n" +
	"\vlineage_ref\x18\t \x01(\tR\n" +
	"lineageRef\x12%\n" +
	"\x0eschema_version\x18\n" +
	" \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0freplay_sequence\x18\r \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\x0e \x01(\tR\x0evalidationHash\"\x83\x04\n" +
	"\x0fTransitionProof\x12\x19\n" +
	"\bproof_id\x18\x01 \x01(\tR\aproofId\x12\x1d\n" +
	"\n" +
	"from_state\x18\x02 \x01(\tR\tfromState\x12\x19\n" +
	"\bto_state\x18\x03 \x01(\tR\atoState\x12#\n" +
	"\rpreimage_hash\x18\x04 \x01(\tR\fpreimageHash\x12#\n" +
	"\rvalidator_set\x18\x05 \x03(\tR\fvalidatorSet\x12#\n" +
	"\rreplay_marker\x18\x06 \x01(\x04R\freplayMarker\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\xda\x04\n" +
	"\vLedgerEntry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12J\n" +
	"\x0fevidence_record\x18\x02 \x01(\v2!.phoenix.ledger.v1.EvidenceRecordR\x0eevidenceRecord\x12!\n" +
	"\fstate_before\x18\x03 \x01(\tR\vstateBefore\x12\x1f\n" +
	"\vstate_after\x18\x04 \x01(\tR\n" +
	"stateAfter\x12M\n" +
	"\x10transition_proof\x18\x05 \x01(\v2\".phoenix.ledger.v1.TransitionProofR\x0ftransitionProof\x12'\n" +
	"\x0freplay_sequence\x18\x06 \x01(\x04R\x0ereplaySequence\x12#\n" +
	"\rcheckpoint_id\x18\a \x01(\tR\fcheckpointId\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\f \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\x8c\x04\n" +
	"\x12VerificationResult\x12'\n" +
	"\x0fverification_id\x18\x01 \x01(\tR\x0everificationId\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\tR\rledgerEntryId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0ftamper_detected\x18\x04 \x01(\bR\x0etamperDetected\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x1a\n" +
	"\bverifier\x18\x06 \x01(\tR\bverifier\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\x96\x04\n" +
	"\x0fChainCheckpoint\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\"\n" +
	"\rlast_entry_id\x18\x02 \x01(\tR\vlastEntryId\x12'\n" +
	"\x0fcumulative_hash\x18\x03 \x01(\tR\x0ecumulativeHash\x12)\n" +
	"\x10validator_quorum\x18\x04 \x03(\tR\x0fvalidatorQuorum\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashBEZCgithub.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/ledgerb\x06proto3"

var (
	file_proto_v1_ledger_proto_rawDescOnce sync.Once
	file_proto_v1_ledger_proto_rawDescData []byte
)

func file_proto_v1_ledger_proto_rawDescGZIP() []byte {
	file_proto_v1_ledger_proto_rawDescOnce.Do(func() {
		file_proto_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_ledger_proto_rawDesc), len(file_proto_v1_ledger_proto_rawDesc)))
	})
	return file_proto_v1_ledger_proto_rawDescData
}

var file_proto_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_ledger_proto_goTypes = []any{
	(*EvidenceRecord)(nil),        // 0: phoenix.ledger.v1.EvidenceRecord
	(*TransitionProof)(nil),       // 1: phoenix.ledger.v1.TransitionProof
	(*LedgerEntry)(nil),           // 2: phoenix.ledger.v1.LedgerEntry
	(*VerificationResult)(nil),    // 3: phoenix.ledger.v1.VerificationResult
	(*ChainCheckpoint)(nil),       // 4: phoenix.ledger.v1.ChainCheckpoint
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_v1_ledger_proto_depIdxs = []int32{
	5,  // 0: phoenix.ledger.v1.EvidenceRecord.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: phoenix.ledger.v1.EvidenceRecord.created_at:type_name -> google.protobuf.Timestamp
	5,  // 2: phoenix.ledger.v1.EvidenceRecord.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: phoenix.ledger.v1.TransitionProof.created_at:type_name -> google.protobuf.Timestamp
	5,  // 4: phoenix.ledger.v1.TransitionProof.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: phoenix.ledger.v1.LedgerEntry.evidence_record:type_name -> phoenix.ledger.v1.EvidenceRecord
	1,  // 6: phoenix.ledger.v1.LedgerEntry.transition_proof:type_name -> phoenix.ledger.v1.TransitionProof
	5,  // 7: phoenix.ledger.v1.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: phoenix.ledger.v1.LedgerEntry.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 9: phoenix.ledger.v1.VerificationResult.created_at:type_name -> google.protobuf.Timestamp
	5,  // 10: phoenix.ledger.v1.VerificationResult.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 11: phoenix.ledger.v1.ChainCheckpoint.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 12: phoenix.ledger.v1.ChainCheckpoint.created_at:type_name -> google.protobuf.Timestamp
	5,  // 13: phoenix.ledger.v1.ChainCheckpoint.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_ledger_proto_init() }
func file_proto_v1_ledger_proto_init() {
	if File_proto_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_ledger_proto_rawDesc), len(file_proto_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_ledger_proto_goTypes,
		DependencyIndexes: file_proto_v1_ledger_proto_depIdxs,
		MessageInfos:      file_proto_v1_ledger_proto_msgTypes,
	}.Build()
	File_proto_v1_ledger_proto = out.File
	file_proto_v1_ledger_proto_goTypes = nil
	file_proto_v1_ledger_proto_depIdxs = nil
}
