/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Enforcement Protocol Definition — Enforcement Requests, Approvals, Execution, Kill Switch
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/enforcement.proto

package enforcement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RollbackPlan defines how to safely reverse an enforcement action.
type RollbackPlan struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RollbackId   string                 `protobuf:"bytes,1,opt,name=rollback_id,json=rollbackId,proto3" json:"rollback_id,omitempty"`
	TargetState  string                 `protobuf:"bytes,2,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	InverseSteps []string               `protobuf:"bytes,3,rep,name=inverse_steps,json=inverseSteps,proto3" json:"inverse_steps,omitempty"`
	Deadline     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Verification string                 `protobuf:"bytes,5,opt,name=verification,proto3" json:"verification,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackPlan) Reset() {
	*x = RollbackPlan{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPlan) ProtoMessage() {}

func (x *RollbackPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPlan.ProtoReflect.Descriptor instead.
func (*RollbackPlan) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{0}
}

func (x *RollbackPlan) GetRollbackId() string {
	if x != nil {
		return x.RollbackId
	}
	return ""
}

func (x *RollbackPlan) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *RollbackPlan) GetInverseSteps() []string {
	if x != nil {
		return x.InverseSteps
	}
	return nil
}

func (x *RollbackPlan) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *RollbackPlan) GetVerification() string {
	if x != nil {
		return x.Verification
	}
	return ""
}

func (x *RollbackPlan) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RollbackPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RollbackPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RollbackPlan) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *RollbackPlan) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *RollbackPlan) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// EnforcementRequest initiates an enforcement action.
// All enforcement actions MUST have a rollback plan and approval chain.
type EnforcementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RollbackPlan  *RollbackPlan          `protobuf:"bytes,6,opt,name=rollback_plan,json=rollbackPlan,proto3" json:"rollback_plan,omitempty"`
	ReplayMarker  uint64                 `protobuf:"varint,7,opt,name=replay_marker,json=replayMarker,proto3" json:"replay_marker,omitempty"`
	ApprovalChain []string               `protobuf:"bytes,8,rep,name=approval_chain,json=approvalChain,proto3" json:"approval_chain,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,12,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,13,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,14,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnforcementRequest) Reset() {
	*x = EnforcementRequest{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementRequest) ProtoMessage() {}

func (x *EnforcementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementRequest.ProtoReflect.Descriptor instead.
func (*EnforcementRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{1}
}

func (x *EnforcementRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnforcementRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *EnforcementRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EnforcementRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *EnforcementRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *EnforcementRequest) GetRollbackPlan() *RollbackPlan {
	if x != nil {
		return x.RollbackPlan
	}
	return nil
}

func (x *EnforcementRequest) GetReplayMarker() uint64 {
	if x != nil {
		return x.ReplayMarker
	}
	return 0
}

func (x *EnforcementRequest) GetApprovalChain() []string {
	if x != nil {
		return x.ApprovalChain
	}
	return nil
}

func (x *EnforcementRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EnforcementRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnforcementRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EnforcementRequest) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EnforcementRequest) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EnforcementRequest) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// EnforcementApproval records an approval or denial of an enforcement request.
type EnforcementApproval struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	RequestId  string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Approver   string                 `protobuf:"bytes,3,opt,name=approver,proto3" json:"approver,omitempty"`
	Decision   string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	Conditions []string               `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Expiry     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Signature  string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnforcementApproval) Reset() {
	*x = EnforcementApproval{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementApproval) ProtoMessage() {}

func (x *EnforcementApproval) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementApproval.ProtoReflect.Descriptor instead.
func (*EnforcementApproval) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{2}
}

func (x *EnforcementApproval) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *EnforcementApproval) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnforcementApproval) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *EnforcementApproval) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *EnforcementApproval) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *EnforcementApproval) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *EnforcementApproval) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EnforcementApproval) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EnforcementApproval) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnforcementApproval) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EnforcementApproval) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EnforcementApproval) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EnforcementApproval) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ExecutionPlan defines the ordered steps for executing an enforcement action.
type ExecutionPlan struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlanId             string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Steps              []string               `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	DeterministicOrder bool                   `protobuf:"varint,3,opt,name=deterministic_order,json=deterministicOrder,proto3" json:"deterministic_order,omitempty"`
	Preconditions      []string               `protobuf:"bytes,4,rep,name=preconditions,proto3" json:"preconditions,omitempty"`
	RollbackSteps      []string               `protobuf:"bytes,5,rep,name=rollback_steps,json=rollbackSteps,proto3" json:"rollback_steps,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionPlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ExecutionPlan) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ExecutionPlan) GetDeterministicOrder() bool {
	if x != nil {
		return x.DeterministicOrder
	}
	return false
}

func (x *ExecutionPlan) GetPreconditions() []string {
	if x != nil {
		return x.Preconditions
	}
	return nil
}

func (x *ExecutionPlan) GetRollbackSteps() []string {
	if x != nil {
		return x.RollbackSteps
	}
	return nil
}

func (x *ExecutionPlan) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ExecutionPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExecutionPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ExecutionPlan) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ExecutionPlan) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ExecutionPlan) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ExecutionResult records the outcome of an enforcement action.
type ExecutionResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ResultId     string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	RequestId    string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success      bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	AppliedSteps []string               `protobuf:"bytes,4,rep,name=applied_steps,json=appliedSteps,proto3" json:"applied_steps,omitempty"`
	Errors       []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	FinalState   string                 `protobuf:"bytes,6,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	ReplayMarker uint64                 `protobuf:"varint,7,opt,name=replay_marker,json=replayMarker,proto3" json:"replay_marker,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionResult) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *ExecutionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutionResult) GetAppliedSteps() []string {
	if x != nil {
		return x.AppliedSteps
	}
	return nil
}

func (x *ExecutionResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ExecutionResult) GetFinalState() string {
	if x != nil {
		return x.FinalState
	}
	return ""
}

func (x *ExecutionResult) GetReplayMarker() uint64 {
	if x != nil {
		return x.ReplayMarker
	}
	return 0
}

func (x *ExecutionResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ExecutionResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExecutionResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ExecutionResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ExecutionResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ExecutionResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// KillSwitchState represents the system-wide kill switch.
// When activated, all non-essential operations MUST halt immediately.
type KillSwitchState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SwitchId           string                 `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	Mode               string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ActivatedBy        string                 `protobuf:"bytes,4,opt,name=activated_by,json=activatedBy,proto3" json:"activated_by,omitempty"`
	Duration           *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	RecoveryConditions []string               `protobuf:"bytes,6,rep,name=recovery_conditions,json=recoveryConditions,proto3" json:"recovery_conditions,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KillSwitchState) Reset() {
	*x = KillSwitchState{}
	mi := &file_proto_v1_enforcement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSwitchState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSwitchState) ProtoMessage() {}

func (x *KillSwitchState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_enforcement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSwitchState.ProtoReflect.Descriptor instead.
func (*KillSwitchState) Descriptor() ([]byte, []int) {
	return file_proto_v1_enforcement_proto_rawDescGZIP(), []int{5}
}

func (x *KillSwitchState) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *KillSwitchState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *KillSwitchState) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KillSwitchState) GetActivatedBy() string {
	if x != nil {
		return x.ActivatedBy
	}
	return ""
}

func (x *KillSwitchState) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *KillSwitchState) GetRecoveryConditions() []string {
	if x != nil {
		return x.RecoveryConditions
	}
	return nil
}

func (x *KillSwitchState) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *KillSwitchState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KillSwitchState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KillSwitchState) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *KillSwitchState) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *KillSwitchState) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_enforcement_proto protoreflect.FileDescriptor

const file_proto_v1_enforcement_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/enforcement.proto\x12\x16phoenix.enforcement.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xe3\x03\n" +
	"\fRollbackPlan\x12\x1f\n" +
	"\vrollback_id\x18\x01 \x01(\tR\n" +
	"rollbackId\x12!\n" +
	"\ftarget_state\x18\x02 \x01(\tR\vtargetState\x12#\n" +
	"\rinverse_steps\x18\x03 \x03(\tR\finverseSteps\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\"\n" +
	"\fverification\x18\x05 \x01(\tR\fverification\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xd5\x04\n" +
	"\x12EnforcementRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12I\n" +
	"\rrollback_plan\x18\x06 \x01(\v2$.phoenix.enforcement.v1.RollbackPlanR\frollbackPlan\x12#\n" +
	"\rreplay_marker\x18\a \x01(\x04R\freplayMarker\x12%\n" +
	"\x0eapproval_chain\x18\b \x03(\tR\rapprovalChain\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\f \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\r \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\x0e \x01(\tR\x0evalidationHash\"\x8f\x04\n" +
	"\x13EnforcementApproval\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bapprover\x18\x03 \x01(\tR\bapprover\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x03(\tR\n" +
	"conditions\x122\n" +
	"\x06expiry\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\xcc\x03\n" +
	"\rExecutionPlan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x14\n" +
	"\x05steps\x18\x02 \x03(\tR\x05steps\x12/\n" +
	"\x13deterministic_order\x18\x03 \x01(\bR\x12deterministicOrder\x12$\n" +
	"\rpreconditions\x18\x04 \x03(\tR\rpreconditions\x12%\n" +
	"\x0erollback_steps\x18\x05 \x03(\tR\rrollbackSteps\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xfa\x03\n" +
	"\x0fExecutionResult\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rapplied_steps\x18\x04 \x03(\tR\fappliedSteps\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12\x1f\n" +
	"\vfinal_state\x18\x06 \x01(\tR\n" +
	"finalState\x12#\n" +
	"\rreplay_marker\x18\a \x01(\x04R\freplayMarker\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\xf5\x03\n" +
	"\x0fKillSwitchState\x12\x1b\n" +
	"\tswitch_id\x18\x01 \x01(\tR\bswitchId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\factivated_by\x18\x04 \x01(\tR\vactivatedBy\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12/\n" +
	"\x13recovery_conditions\x18\x06 \x03(\tR\x12recoveryConditions\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashB;Z9github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/enforcementb\x06proto3"

var (
	file_proto_v1_enforcement_proto_rawDescOnce sync.Once
	file_proto_v1_enforcement_proto_rawDescData []byte
)

func file_proto_v1_enforcement_proto_rawDescGZIP() []byte {
	file_proto_v1_enforcement_proto_rawDescOnce.Do(func() {
		file_proto_v1_enforcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_enforcement_proto_rawDesc), len(file_proto_v1_enforcement_proto_rawDesc)))
	})
	return file_proto_v1_enforcement_proto_rawDescData
}

var file_proto_v1_enforcement_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_enforcement_proto_goTypes = []any{
	(*RollbackPlan)(nil),          // 0: phoenix.enforcement.v1.RollbackPlan
	(*EnforcementRequest)(nil),    // 1: phoenix.enforcement.v1.EnforcementRequest
	(*EnforcementApproval)(nil),   // 2: phoenix.enforcement.v1.EnforcementApproval
	(*ExecutionPlan)(nil),         // 3: phoenix.enforcement.v1.ExecutionPlan
	(*ExecutionResult)(nil),       // 4: phoenix.enforcement.v1.ExecutionResult
	(*KillSwitchState)(nil),       // 5: phoenix.enforcement.v1.KillSwitchState
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_proto_v1_enforcement_proto_depIdxs = []int32{
	6,  // 0: phoenix.enforcement.v1.RollbackPlan.deadline:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.enforcement.v1.RollbackPlan.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.enforcement.v1.RollbackPlan.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: phoenix.enforcement.v1.EnforcementRequest.timeout:type_name -> google.protobuf.Duration
	0,  // 4: phoenix.enforcement.v1.EnforcementRequest.rollback_plan:type_name -> phoenix.enforcement.v1.RollbackPlan
	6,  // 5: phoenix.enforcement.v1.EnforcementRequest.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: phoenix.enforcement.v1.EnforcementRequest.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: phoenix.enforcement.v1.EnforcementApproval.expiry:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.enforcement.v1.EnforcementApproval.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.enforcement.v1.EnforcementApproval.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.enforcement.v1.ExecutionPlan.created_at:type_name -> google.protobuf.Timestamp
	6,  // 11: phoenix.enforcement.v1.ExecutionPlan.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 12: phoenix.enforcement.v1.ExecutionResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 13: phoenix.enforcement.v1.ExecutionResult.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 14: phoenix.enforcement.v1.KillSwitchState.duration:type_name -> google.protobuf.Duration
	6,  // 15: phoenix.enforcement.v1.KillSwitchState.created_at:type_name -> google.protobuf.Timestamp
	6,  // 16: phoenix.enforcement.v1.KillSwitchState.updated_at:type_name -> google.protobuf.Timestamp
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_v1_enforcement_proto_init() }
func file_proto_v1_enforcement_proto_init() {
	if File_proto_v1_enforcement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_enforcement_proto_rawDesc), len(file_proto_v1_enforcement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_enforcement_proto_goTypes,
		DependencyIndexes: file_proto_v1_enforcement_proto_depIdxs,
		MessageInfos:      file_proto_v1_enforcement_proto_msgTypes,
	}.Build()
	File_proto_v1_enforcement_proto = out.File
	file_proto_v1_enforcement_proto_goTypes = nil
	file_proto_v1_enforcement_proto_depIdxs = nil
}
