/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// FSM Serialization Schema — Warden and Consensus States
// ALL repos depend on PhoenixCore contracts.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/fsm/fsm.proto

package fsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemState int32

const (
	SystemState_SYSTEM_STATE_UNSPECIFIED SystemState = 0
	SystemState_SYSTEM_STATE_SAFE        SystemState = 1
	SystemState_SYSTEM_STATE_WATCH       SystemState = 2
	SystemState_SYSTEM_STATE_SUSPICIOUS  SystemState = 3
	SystemState_SYSTEM_STATE_CRITICAL    SystemState = 4
	SystemState_SYSTEM_STATE_COMPROMISED SystemState = 5
)

// Enum value maps for SystemState.
var (
	SystemState_name = map[int32]string{
		0: "SYSTEM_STATE_UNSPECIFIED",
		1: "SYSTEM_STATE_SAFE",
		2: "SYSTEM_STATE_WATCH",
		3: "SYSTEM_STATE_SUSPICIOUS",
		4: "SYSTEM_STATE_CRITICAL",
		5: "SYSTEM_STATE_COMPROMISED",
	}
	SystemState_value = map[string]int32{
		"SYSTEM_STATE_UNSPECIFIED": 0,
		"SYSTEM_STATE_SAFE":        1,
		"SYSTEM_STATE_WATCH":       2,
		"SYSTEM_STATE_SUSPICIOUS":  3,
		"SYSTEM_STATE_CRITICAL":    4,
		"SYSTEM_STATE_COMPROMISED": 5,
	}
)

func (x SystemState) Enum() *SystemState {
	p := new(SystemState)
	*p = x
	return p
}

func (x SystemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_fsm_fsm_proto_enumTypes[0].Descriptor()
}

func (SystemState) Type() protoreflect.EnumType {
	return &file_proto_v1_fsm_fsm_proto_enumTypes[0]
}

func (x SystemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemState.Descriptor instead.
func (SystemState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_fsm_fsm_proto_rawDescGZIP(), []int{0}
}

// WardenState represents the deterministic state of the Warden FSM.
type WardenState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CurrentState     SystemState            `protobuf:"varint,1,opt,name=current_state,json=currentState,proto3,enum=phoenix.fsm.v1.SystemState" json:"current_state,omitempty"`
	Locked           bool                   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
	LastTransitionNs uint64                 `protobuf:"varint,3,opt,name=last_transition_ns,json=lastTransitionNs,proto3" json:"last_transition_ns,omitempty"` // Fixed-width monotonic timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WardenState) Reset() {
	*x = WardenState{}
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WardenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WardenState) ProtoMessage() {}

func (x *WardenState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WardenState.ProtoReflect.Descriptor instead.
func (*WardenState) Descriptor() ([]byte, []int) {
	return file_proto_v1_fsm_fsm_proto_rawDescGZIP(), []int{0}
}

func (x *WardenState) GetCurrentState() SystemState {
	if x != nil {
		return x.CurrentState
	}
	return SystemState_SYSTEM_STATE_UNSPECIFIED
}

func (x *WardenState) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *WardenState) GetLastTransitionNs() uint64 {
	if x != nil {
		return x.LastTransitionNs
	}
	return 0
}

// ConsensusState represents the distributed agreement state.
type ConsensusState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActiveNodes     uint32                 `protobuf:"varint,1,opt,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	QuorumWeightRaw uint64                 `protobuf:"varint,2,opt,name=quorum_weight_raw,json=quorumWeightRaw,proto3" json:"quorum_weight_raw,omitempty"` // Scaled integer to avoid floating point (weight * 1,000,000)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsensusState) Reset() {
	*x = ConsensusState{}
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusState) ProtoMessage() {}

func (x *ConsensusState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusState.ProtoReflect.Descriptor instead.
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return file_proto_v1_fsm_fsm_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusState) GetActiveNodes() uint32 {
	if x != nil {
		return x.ActiveNodes
	}
	return 0
}

func (x *ConsensusState) GetQuorumWeightRaw() uint64 {
	if x != nil {
		return x.QuorumWeightRaw
	}
	return 0
}

// FSMStateBlock is the bit-level serializable block for a single point in time.
type FSMStateBlock struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Warden    *WardenState           `protobuf:"bytes,1,opt,name=warden,proto3" json:"warden,omitempty"`
	Consensus *ConsensusState        `protobuf:"bytes,2,opt,name=consensus,proto3" json:"consensus,omitempty"`
	// Chain of Custody
	PreStateHash  string `protobuf:"bytes,3,opt,name=pre_state_hash,json=preStateHash,proto3" json:"pre_state_hash,omitempty"`
	PostStateHash string `protobuf:"bytes,4,opt,name=post_state_hash,json=postStateHash,proto3" json:"post_state_hash,omitempty"`
	// Mandatory metadata
	ReplaySequence uint64 `protobuf:"varint,5,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string `protobuf:"bytes,6,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FSMStateBlock) Reset() {
	*x = FSMStateBlock{}
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSMStateBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSMStateBlock) ProtoMessage() {}

func (x *FSMStateBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_fsm_fsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSMStateBlock.ProtoReflect.Descriptor instead.
func (*FSMStateBlock) Descriptor() ([]byte, []int) {
	return file_proto_v1_fsm_fsm_proto_rawDescGZIP(), []int{2}
}

func (x *FSMStateBlock) GetWarden() *WardenState {
	if x != nil {
		return x.Warden
	}
	return nil
}

func (x *FSMStateBlock) GetConsensus() *ConsensusState {
	if x != nil {
		return x.Consensus
	}
	return nil
}

func (x *FSMStateBlock) GetPreStateHash() string {
	if x != nil {
		return x.PreStateHash
	}
	return ""
}

func (x *FSMStateBlock) GetPostStateHash() string {
	if x != nil {
		return x.PostStateHash
	}
	return ""
}

func (x *FSMStateBlock) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *FSMStateBlock) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_fsm_fsm_proto protoreflect.FileDescriptor

const file_proto_v1_fsm_fsm_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/fsm/fsm.proto\x12\x0ephoenix.fsm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\vWardenState\x12@\n" +
	"\rcurrent_state\x18\x01 \x01(\x0e2\x1b.phoenix.fsm.v1.SystemStateR\fcurrentState\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\bR\x06locked\x12,\n" +
	"\x12last_transition_ns\x18\x03 \x01(\x04R\x10lastTransitionNs\"_\n" +
	"\x0eConsensusState\x12!\n" +
	"\factive_nodes\x18\x01 \x01(\rR\vactiveNodes\x12*\n" +
	"\x11quorum_weight_raw\x18\x02 \x01(\x04R\x0fquorumWeightRaw\"\xa2\x02\n" +
	"\rFSMStateBlock\x123\n" +
	"\x06warden\x18\x01 \x01(\v2\x1b.phoenix.fsm.v1.WardenStateR\x06warden\x12<\n" +
	"\tconsensus\x18\x02 \x01(\v2\x1e.phoenix.fsm.v1.ConsensusStateR\tconsensus\x12$\n" +
	"\x0epre_state_hash\x18\x03 \x01(\tR\fpreStateHash\x12&\n" +
	"\x0fpost_state_hash\x18\x04 \x01(\tR\rpostStateHash\x12'\n" +
	"\x0freplay_sequence\x18\x05 \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\x06 \x01(\tR\x0evalidationHash*\xb0\x01\n" +
	"\vSystemState\x12\x1c\n" +
	"\x18SYSTEM_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SYSTEM_STATE_SAFE\x10\x01\x12\x16\n" +
	"\x12SYSTEM_STATE_WATCH\x10\x02\x12\x1b\n" +
	"\x17SYSTEM_STATE_SUSPICIOUS\x10\x03\x12\x19\n" +
	"\x15SYSTEM_STATE_CRITICAL\x10\x04\x12\x1c\n" +
	"\x18SYSTEM_STATE_COMPROMISED\x10\x05B3Z1github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/fsmb\x06proto3"

var (
	file_proto_v1_fsm_fsm_proto_rawDescOnce sync.Once
	file_proto_v1_fsm_fsm_proto_rawDescData []byte
)

func file_proto_v1_fsm_fsm_proto_rawDescGZIP() []byte {
	file_proto_v1_fsm_fsm_proto_rawDescOnce.Do(func() {
		file_proto_v1_fsm_fsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_fsm_fsm_proto_rawDesc), len(file_proto_v1_fsm_fsm_proto_rawDesc)))
	})
	return file_proto_v1_fsm_fsm_proto_rawDescData
}

var file_proto_v1_fsm_fsm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_fsm_fsm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_fsm_fsm_proto_goTypes = []any{
	(SystemState)(0),       // 0: phoenix.fsm.v1.SystemState
	(*WardenState)(nil),    // 1: phoenix.fsm.v1.WardenState
	(*ConsensusState)(nil), // 2: phoenix.fsm.v1.ConsensusState
	(*FSMStateBlock)(nil),  // 3: phoenix.fsm.v1.FSMStateBlock
}
var file_proto_v1_fsm_fsm_proto_depIdxs = []int32{
	0, // 0: phoenix.fsm.v1.WardenState.current_state:type_name -> phoenix.fsm.v1.SystemState
	1, // 1: phoenix.fsm.v1.FSMStateBlock.warden:type_name -> phoenix.fsm.v1.WardenState
	2, // 2: phoenix.fsm.v1.FSMStateBlock.consensus:type_name -> phoenix.fsm.v1.ConsensusState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_fsm_fsm_proto_init() }
func file_proto_v1_fsm_fsm_proto_init() {
	if File_proto_v1_fsm_fsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_fsm_fsm_proto_rawDesc), len(file_proto_v1_fsm_fsm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_fsm_fsm_proto_goTypes,
		DependencyIndexes: file_proto_v1_fsm_fsm_proto_depIdxs,
		EnumInfos:         file_proto_v1_fsm_fsm_proto_enumTypes,
		MessageInfos:      file_proto_v1_fsm_fsm_proto_msgTypes,
	}.Build()
	File_proto_v1_fsm_fsm_proto = out.File
	file_proto_v1_fsm_fsm_proto_goTypes = nil
	file_proto_v1_fsm_fsm_proto_depIdxs = nil
}
