/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Event Envelope Protocol Definition
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope is the canonical envelope for all events in the PhoenixOS ecosystem.
// Every event emitted by any component MUST be wrapped in this envelope.
// The envelope provides deterministic replay, causal ordering, evidence hashing,
// and trust scoring for every event that flows through the system.
type EventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this event instance
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Semantic version of the event schema
	EventVersion string `protobuf:"bytes,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	// Fully qualified event type (e.g., "phoenix.guard.state_transition")
	EventType string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Wall-clock timestamp of event creation
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Monotonic nanosecond counter for causal ordering within a single node
	MonotonicTime uint64 `protobuf:"varint,5,opt,name=monotonic_time,json=monotonicTime,proto3" json:"monotonic_time,omitempty"`
	// Repository that produced this event
	SourceRepo string `protobuf:"bytes,6,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	// Component within the source repo that produced this event
	SourceComponent string `protobuf:"bytes,7,opt,name=source_component,json=sourceComponent,proto3" json:"source_component,omitempty"`
	// ID of the parent event that caused this event (empty if root)
	ParentEvent string `protobuf:"bytes,8,opt,name=parent_event,json=parentEvent,proto3" json:"parent_event,omitempty"`
	// Correlation ID for tracing a logical operation across components
	CorrelationId string `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Ordered list of ancestor event IDs forming the causal chain
	CausalChain []string `protobuf:"bytes,10,rep,name=causal_chain,json=causalChain,proto3" json:"causal_chain,omitempty"`
	// Monotonically increasing sequence number for deterministic replay
	ReplaySequence uint64 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	// Cryptographic hash of the evidence supporting this event
	EvidenceHash string `protobuf:"bytes,12,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	// Trust score assigned to this event (0.0 = untrusted, 1.0 = fully verified)
	TrustScore float64 `protobuf:"fixed64,13,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	// Cryptographic signature of the event envelope
	Signature string `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`
	// Hash of the serialized payload for integrity verification
	PayloadHash string `protobuf:"bytes,15,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	// Schema version for this message type
	SchemaVersion string `protobuf:"bytes,16,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Timestamp when this record was first created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when this record was last updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Hash used to validate the integrity of this message
	ValidationHash string `protobuf:"bytes,19,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_proto_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventEnvelope) GetMonotonicTime() uint64 {
	if x != nil {
		return x.MonotonicTime
	}
	return 0
}

func (x *EventEnvelope) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EventEnvelope) GetSourceComponent() string {
	if x != nil {
		return x.SourceComponent
	}
	return ""
}

func (x *EventEnvelope) GetParentEvent() string {
	if x != nil {
		return x.ParentEvent
	}
	return ""
}

func (x *EventEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventEnvelope) GetCausalChain() []string {
	if x != nil {
		return x.CausalChain
	}
	return nil
}

func (x *EventEnvelope) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EventEnvelope) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *EventEnvelope) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *EventEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EventEnvelope) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EventEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventEnvelope) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EventEnvelope) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_event_proto protoreflect.FileDescriptor

const file_proto_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/event.proto\x12\x10phoenix.event.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x05\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12#\n" +
	"\revent_version\x18\x02 \x01(\tR\feventVersion\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0emonotonic_time\x18\x05 \x01(\x04R\rmonotonicTime\x12\x1f\n" +
	"\vsource_repo\x18\x06 \x01(\tR\n" +
	"sourceRepo\x12)\n" +
	"\x10source_component\x18\a \x01(\tR\x0fsourceComponent\x12!\n" +
	"\fparent_event\x18\b \x01(\tR\vparentEvent\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausal_chain\x18\n" +
	" \x03(\tR\vcausalChain\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12#\n" +
	"\revidence_hash\x18\f \x01(\tR\fevidenceHash\x12\x1f\n" +
	"\vtrust_score\x18\r \x01(\x01R\n" +
	"trustScore\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\tR\tsignature\x12!\n" +
	"\fpayload_hash\x18\x0f \x01(\tR\vpayloadHash\x12%\n" +
	"\x0eschema_version\x18\x10 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12'\n" +
	"\x0fvalidation_hash\x18\x13 \x01(\tR\x0evalidationHashB5Z3github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/eventb\x06proto3"

var (
	file_proto_v1_event_proto_rawDescOnce sync.Once
	file_proto_v1_event_proto_rawDescData []byte
)

func file_proto_v1_event_proto_rawDescGZIP() []byte {
	file_proto_v1_event_proto_rawDescOnce.Do(func() {
		file_proto_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_event_proto_rawDesc), len(file_proto_v1_event_proto_rawDesc)))
	})
	return file_proto_v1_event_proto_rawDescData
}

var file_proto_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_event_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: phoenix.event.v1.EventEnvelope
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_v1_event_proto_depIdxs = []int32{
	1, // 0: phoenix.event.v1.EventEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: phoenix.event.v1.EventEnvelope.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: phoenix.event.v1.EventEnvelope.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_event_proto_init() }
func file_proto_v1_event_proto_init() {
	if File_proto_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_event_proto_rawDesc), len(file_proto_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_event_proto_goTypes,
		DependencyIndexes: file_proto_v1_event_proto_depIdxs,
		MessageInfos:      file_proto_v1_event_proto_msgTypes,
	}.Build()
	File_proto_v1_event_proto = out.File
	file_proto_v1_event_proto_goTypes = nil
	file_proto_v1_event_proto_depIdxs = nil
}
