/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Distributed Protocol Definition — Node Identity, Consensus, Replication, Quorum
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/distributed.proto

package distributed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeIdentity represents a node in the distributed PhoenixOS topology.
type NodeIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Repo           string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	AuthorityLevel string                 `protobuf:"bytes,3,opt,name=authority_level,json=authorityLevel,proto3" json:"authority_level,omitempty"`
	PublicKey      string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Epoch          uint64                 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_proto_v1_distributed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *NodeIdentity) GetAuthorityLevel() string {
	if x != nil {
		return x.AuthorityLevel
	}
	return ""
}

func (x *NodeIdentity) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodeIdentity) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NodeIdentity) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NodeIdentity) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *NodeIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NodeIdentity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *NodeIdentity) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *NodeIdentity) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *NodeIdentity) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// AuthorityCertificate certifies a node's authority within a given scope.
type AuthorityCertificate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertId         string                 `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AuthorityScope string                 `protobuf:"bytes,3,opt,name=authority_scope,json=authorityScope,proto3" json:"authority_scope,omitempty"`
	Issuer         string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Signature      string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorityCertificate) Reset() {
	*x = AuthorityCertificate{}
	mi := &file_proto_v1_distributed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorityCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorityCertificate) ProtoMessage() {}

func (x *AuthorityCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorityCertificate.ProtoReflect.Descriptor instead.
func (*AuthorityCertificate) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorityCertificate) GetCertId() string {
	if x != nil {
		return x.CertId
	}
	return ""
}

func (x *AuthorityCertificate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AuthorityCertificate) GetAuthorityScope() string {
	if x != nil {
		return x.AuthorityScope
	}
	return ""
}

func (x *AuthorityCertificate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthorityCertificate) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AuthorityCertificate) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AuthorityCertificate) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AuthorityCertificate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuthorityCertificate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AuthorityCertificate) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *AuthorityCertificate) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *AuthorityCertificate) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ReplicationEvent records a ledger replication across nodes.
type ReplicationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplicationId string                 `protobuf:"bytes,1,opt,name=replication_id,json=replicationId,proto3" json:"replication_id,omitempty"`
	LedgerRef     string                 `protobuf:"bytes,2,opt,name=ledger_ref,json=ledgerRef,proto3" json:"ledger_ref,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	SourceNode    string                 `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	TargetNodes   []string               `protobuf:"bytes,5,rep,name=target_nodes,json=targetNodes,proto3" json:"target_nodes,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicationEvent) Reset() {
	*x = ReplicationEvent{}
	mi := &file_proto_v1_distributed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationEvent) ProtoMessage() {}

func (x *ReplicationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationEvent.ProtoReflect.Descriptor instead.
func (*ReplicationEvent) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationEvent) GetReplicationId() string {
	if x != nil {
		return x.ReplicationId
	}
	return ""
}

func (x *ReplicationEvent) GetLedgerRef() string {
	if x != nil {
		return x.LedgerRef
	}
	return ""
}

func (x *ReplicationEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReplicationEvent) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *ReplicationEvent) GetTargetNodes() []string {
	if x != nil {
		return x.TargetNodes
	}
	return nil
}

func (x *ReplicationEvent) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ReplicationEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ReplicationEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplicationEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReplicationEvent) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ReplicationEvent) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ReplicationEvent) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ConsensusState represents the current consensus state of the distributed system.
type ConsensusState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsensusId     string                 `protobuf:"bytes,1,opt,name=consensus_id,json=consensusId,proto3" json:"consensus_id,omitempty"`
	Term            uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader          string                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Quorum          []string               `protobuf:"bytes,4,rep,name=quorum,proto3" json:"quorum,omitempty"`
	CommitIndex     uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	DivergenceState string                 `protobuf:"bytes,6,opt,name=divergence_state,json=divergenceState,proto3" json:"divergence_state,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsensusState) Reset() {
	*x = ConsensusState{}
	mi := &file_proto_v1_distributed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusState) ProtoMessage() {}

func (x *ConsensusState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusState.ProtoReflect.Descriptor instead.
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{3}
}

func (x *ConsensusState) GetConsensusId() string {
	if x != nil {
		return x.ConsensusId
	}
	return ""
}

func (x *ConsensusState) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ConsensusState) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *ConsensusState) GetQuorum() []string {
	if x != nil {
		return x.Quorum
	}
	return nil
}

func (x *ConsensusState) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *ConsensusState) GetDivergenceState() string {
	if x != nil {
		return x.DivergenceState
	}
	return ""
}

func (x *ConsensusState) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ConsensusState) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConsensusState) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConsensusState) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ConsensusState) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ConsensusState) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// QuorumProof provides cryptographic proof that a quorum was reached.
type QuorumProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofId       string                 `protobuf:"bytes,1,opt,name=proof_id,json=proofId,proto3" json:"proof_id,omitempty"`
	AcceptedNodes []string               `protobuf:"bytes,2,rep,name=accepted_nodes,json=acceptedNodes,proto3" json:"accepted_nodes,omitempty"`
	Threshold     uint32                 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Signatures    []string               `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	EvidenceHash  string                 `protobuf:"bytes,5,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuorumProof) Reset() {
	*x = QuorumProof{}
	mi := &file_proto_v1_distributed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumProof) ProtoMessage() {}

func (x *QuorumProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumProof.ProtoReflect.Descriptor instead.
func (*QuorumProof) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{4}
}

func (x *QuorumProof) GetProofId() string {
	if x != nil {
		return x.ProofId
	}
	return ""
}

func (x *QuorumProof) GetAcceptedNodes() []string {
	if x != nil {
		return x.AcceptedNodes
	}
	return nil
}

func (x *QuorumProof) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *QuorumProof) GetSignatures() []string {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *QuorumProof) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *QuorumProof) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *QuorumProof) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *QuorumProof) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *QuorumProof) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *QuorumProof) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *QuorumProof) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SynchronizationResult records the outcome of a node synchronization.
type SynchronizationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SyncId         string                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Lag            *durationpb.Duration   `protobuf:"bytes,4,opt,name=lag,proto3" json:"lag,omitempty"`
	RecoveredState string                 `protobuf:"bytes,5,opt,name=recovered_state,json=recoveredState,proto3" json:"recovered_state,omitempty"`
	ReplayMarker   uint64                 `protobuf:"varint,6,opt,name=replay_marker,json=replayMarker,proto3" json:"replay_marker,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SynchronizationResult) Reset() {
	*x = SynchronizationResult{}
	mi := &file_proto_v1_distributed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynchronizationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynchronizationResult) ProtoMessage() {}

func (x *SynchronizationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_distributed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynchronizationResult.ProtoReflect.Descriptor instead.
func (*SynchronizationResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_distributed_proto_rawDescGZIP(), []int{5}
}

func (x *SynchronizationResult) GetSyncId() string {
	if x != nil {
		return x.SyncId
	}
	return ""
}

func (x *SynchronizationResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SynchronizationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SynchronizationResult) GetLag() *durationpb.Duration {
	if x != nil {
		return x.Lag
	}
	return nil
}

func (x *SynchronizationResult) GetRecoveredState() string {
	if x != nil {
		return x.RecoveredState
	}
	return ""
}

func (x *SynchronizationResult) GetReplayMarker() uint64 {
	if x != nil {
		return x.ReplayMarker
	}
	return 0
}

func (x *SynchronizationResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SynchronizationResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SynchronizationResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SynchronizationResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SynchronizationResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SynchronizationResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_distributed_proto protoreflect.FileDescriptor

const file_proto_v1_distributed_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/distributed.proto\x12\x16phoenix.distributed.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xc1\x03\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12'\n" +
	"\x0fauthority_level\x18\x03 \x01(\tR\x0eauthorityLevel\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x04R\x05epoch\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xf2\x03\n" +
	"\x14AuthorityCertificate\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\tR\x06certId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fauthority_scope\x18\x03 \x01(\tR\x0eauthorityScope\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xe2\x03\n" +
	"\x10ReplicationEvent\x12%\n" +
	"\x0ereplication_id\x18\x01 \x01(\tR\rreplicationId\x12\x1d\n" +
	"\n" +
	"ledger_ref\x18\x02 \x01(\tR\tledgerRef\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1f\n" +
	"\vsource_node\x18\x04 \x01(\tR\n" +
	"sourceNode\x12!\n" +
	"\ftarget_nodes\x18\x05 \x03(\tR\vtargetNodes\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xd5\x03\n" +
	"\x0eConsensusState\x12!\n" +
	"\fconsensus_id\x18\x01 \x01(\tR\vconsensusId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\x12\x16\n" +
	"\x06quorum\x18\x04 \x03(\tR\x06quorum\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12)\n" +
	"\x10divergence_state\x18\x06 \x01(\tR\x0fdivergenceState\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xc2\x03\n" +
	"\vQuorumProof\x12\x19\n" +
	"\bproof_id\x18\x01 \x01(\tR\aproofId\x12%\n" +
	"\x0eaccepted_nodes\x18\x02 \x03(\tR\racceptedNodes\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\x12\x1e\n" +
	"\n" +
	"signatures\x18\x04 \x03(\tR\n" +
	"signatures\x12#\n" +
	"\revidence_hash\x18\x05 \x01(\tR\fevidenceHash\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xec\x03\n" +
	"\x15SynchronizationResult\x12\x17\n" +
	"\async_id\x18\x01 \x01(\tR\x06syncId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x03lag\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03lag\x12'\n" +
	"\x0frecovered_state\x18\x05 \x01(\tR\x0erecoveredState\x12#\n" +
	"\rreplay_marker\x18\x06 \x01(\x04R\freplayMarker\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashB;Z9github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/distributedb\x06proto3"

var (
	file_proto_v1_distributed_proto_rawDescOnce sync.Once
	file_proto_v1_distributed_proto_rawDescData []byte
)

func file_proto_v1_distributed_proto_rawDescGZIP() []byte {
	file_proto_v1_distributed_proto_rawDescOnce.Do(func() {
		file_proto_v1_distributed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_distributed_proto_rawDesc), len(file_proto_v1_distributed_proto_rawDesc)))
	})
	return file_proto_v1_distributed_proto_rawDescData
}

var file_proto_v1_distributed_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_distributed_proto_goTypes = []any{
	(*NodeIdentity)(nil),          // 0: phoenix.distributed.v1.NodeIdentity
	(*AuthorityCertificate)(nil),  // 1: phoenix.distributed.v1.AuthorityCertificate
	(*ReplicationEvent)(nil),      // 2: phoenix.distributed.v1.ReplicationEvent
	(*ConsensusState)(nil),        // 3: phoenix.distributed.v1.ConsensusState
	(*QuorumProof)(nil),           // 4: phoenix.distributed.v1.QuorumProof
	(*SynchronizationResult)(nil), // 5: phoenix.distributed.v1.SynchronizationResult
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_proto_v1_distributed_proto_depIdxs = []int32{
	6,  // 0: phoenix.distributed.v1.NodeIdentity.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.distributed.v1.NodeIdentity.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.distributed.v1.AuthorityCertificate.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.distributed.v1.AuthorityCertificate.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: phoenix.distributed.v1.AuthorityCertificate.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: phoenix.distributed.v1.ReplicationEvent.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: phoenix.distributed.v1.ReplicationEvent.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: phoenix.distributed.v1.ConsensusState.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.distributed.v1.ConsensusState.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.distributed.v1.QuorumProof.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.distributed.v1.QuorumProof.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 11: phoenix.distributed.v1.SynchronizationResult.lag:type_name -> google.protobuf.Duration
	6,  // 12: phoenix.distributed.v1.SynchronizationResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 13: phoenix.distributed.v1.SynchronizationResult.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_distributed_proto_init() }
func file_proto_v1_distributed_proto_init() {
	if File_proto_v1_distributed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_distributed_proto_rawDesc), len(file_proto_v1_distributed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_distributed_proto_goTypes,
		DependencyIndexes: file_proto_v1_distributed_proto_depIdxs,
		MessageInfos:      file_proto_v1_distributed_proto_msgTypes,
	}.Build()
	File_proto_v1_distributed_proto = out.File
	file_proto_v1_distributed_proto_goTypes = nil
	file_proto_v1_distributed_proto_depIdxs = nil
}
