/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Trace Protocol Definition — Lineage Graphs, Causal Chains, Process Graphs
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/trace.proto

package trace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TraceNode represents a single node in the causal trace graph.
type TraceNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SourceEvent    string                 `protobuf:"bytes,2,opt,name=source_event,json=sourceEvent,proto3" json:"source_event,omitempty"`
	ProcessLineage []string               `protobuf:"bytes,3,rep,name=process_lineage,json=processLineage,proto3" json:"process_lineage,omitempty"`
	TelemetryRefs  []string               `protobuf:"bytes,4,rep,name=telemetry_refs,json=telemetryRefs,proto3" json:"telemetry_refs,omitempty"`
	EvidenceRefs   []string               `protobuf:"bytes,5,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Trust          float64                `protobuf:"fixed64,7,opt,name=trust,proto3" json:"trust,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TraceNode) Reset() {
	*x = TraceNode{}
	mi := &file_proto_v1_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceNode) ProtoMessage() {}

func (x *TraceNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceNode.ProtoReflect.Descriptor instead.
func (*TraceNode) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{0}
}

func (x *TraceNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TraceNode) GetSourceEvent() string {
	if x != nil {
		return x.SourceEvent
	}
	return ""
}

func (x *TraceNode) GetProcessLineage() []string {
	if x != nil {
		return x.ProcessLineage
	}
	return nil
}

func (x *TraceNode) GetTelemetryRefs() []string {
	if x != nil {
		return x.TelemetryRefs
	}
	return nil
}

func (x *TraceNode) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *TraceNode) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TraceNode) GetTrust() float64 {
	if x != nil {
		return x.Trust
	}
	return 0
}

func (x *TraceNode) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TraceNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TraceNode) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TraceNode) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *TraceNode) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *TraceNode) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// TraceEdge represents a directed edge between two trace nodes
// with causal strength and ordering metadata.
type TraceEdge struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EdgeId         string                 `protobuf:"bytes,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	FromNode       string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode         string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	RelationType   string                 `protobuf:"bytes,4,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	CausalStrength float64                `protobuf:"fixed64,5,opt,name=causal_strength,json=causalStrength,proto3" json:"causal_strength,omitempty"`
	Ordering       uint64                 `protobuf:"varint,6,opt,name=ordering,proto3" json:"ordering,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TraceEdge) Reset() {
	*x = TraceEdge{}
	mi := &file_proto_v1_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEdge) ProtoMessage() {}

func (x *TraceEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEdge.ProtoReflect.Descriptor instead.
func (*TraceEdge) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{1}
}

func (x *TraceEdge) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *TraceEdge) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *TraceEdge) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *TraceEdge) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *TraceEdge) GetCausalStrength() float64 {
	if x != nil {
		return x.CausalStrength
	}
	return 0
}

func (x *TraceEdge) GetOrdering() uint64 {
	if x != nil {
		return x.Ordering
	}
	return 0
}

func (x *TraceEdge) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TraceEdge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TraceEdge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TraceEdge) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *TraceEdge) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *TraceEdge) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// LineageGraph is the complete causal graph for a trace session.
type LineageGraph struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GraphId    string                 `protobuf:"bytes,1,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	Nodes      []*TraceNode           `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges      []*TraceEdge           `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	Checkpoint string                 `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Root       string                 `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LineageGraph) Reset() {
	*x = LineageGraph{}
	mi := &file_proto_v1_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineageGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageGraph) ProtoMessage() {}

func (x *LineageGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageGraph.ProtoReflect.Descriptor instead.
func (*LineageGraph) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{2}
}

func (x *LineageGraph) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *LineageGraph) GetNodes() []*TraceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LineageGraph) GetEdges() []*TraceEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *LineageGraph) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *LineageGraph) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *LineageGraph) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *LineageGraph) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LineageGraph) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LineageGraph) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *LineageGraph) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *LineageGraph) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// CausalChain represents an ordered sequence of causally linked events.
type CausalChain struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChainId        string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	OrderedNodes   []string               `protobuf:"bytes,2,rep,name=ordered_nodes,json=orderedNodes,proto3" json:"ordered_nodes,omitempty"`
	ParentLinks    []string               `protobuf:"bytes,3,rep,name=parent_links,json=parentLinks,proto3" json:"parent_links,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,4,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	Explanation    string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ValidationHash string                 `protobuf:"bytes,10,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CausalChain) Reset() {
	*x = CausalChain{}
	mi := &file_proto_v1_trace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalChain) ProtoMessage() {}

func (x *CausalChain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalChain.ProtoReflect.Descriptor instead.
func (*CausalChain) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{3}
}

func (x *CausalChain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *CausalChain) GetOrderedNodes() []string {
	if x != nil {
		return x.OrderedNodes
	}
	return nil
}

func (x *CausalChain) GetParentLinks() []string {
	if x != nil {
		return x.ParentLinks
	}
	return nil
}

func (x *CausalChain) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *CausalChain) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *CausalChain) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *CausalChain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CausalChain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CausalChain) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *CausalChain) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ProcessGraph represents a process tree with lifecycle metadata.
type ProcessGraph struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Pid       string                 `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	ParentPid string                 `protobuf:"bytes,3,opt,name=parent_pid,json=parentPid,proto3" json:"parent_pid,omitempty"`
	NodeLinks []string               `protobuf:"bytes,4,rep,name=node_links,json=nodeLinks,proto3" json:"node_links,omitempty"`
	Lifecycle string                 `protobuf:"bytes,5,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Host      string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessGraph) Reset() {
	*x = ProcessGraph{}
	mi := &file_proto_v1_trace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessGraph) ProtoMessage() {}

func (x *ProcessGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessGraph.ProtoReflect.Descriptor instead.
func (*ProcessGraph) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessGraph) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessGraph) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ProcessGraph) GetParentPid() string {
	if x != nil {
		return x.ParentPid
	}
	return ""
}

func (x *ProcessGraph) GetNodeLinks() []string {
	if x != nil {
		return x.NodeLinks
	}
	return nil
}

func (x *ProcessGraph) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ProcessGraph) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProcessGraph) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ProcessGraph) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProcessGraph) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProcessGraph) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ProcessGraph) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ProcessGraph) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// EvidenceLink connects a piece of evidence to a trace node.
type EvidenceLink struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	LinkId      string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	EvidenceId  string                 `protobuf:"bytes,2,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	TraceNodeId string                 `protobuf:"bytes,3,opt,name=trace_node_id,json=traceNodeId,proto3" json:"trace_node_id,omitempty"`
	Relation    string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Hash        string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceLink) Reset() {
	*x = EvidenceLink{}
	mi := &file_proto_v1_trace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceLink) ProtoMessage() {}

func (x *EvidenceLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_trace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceLink.ProtoReflect.Descriptor instead.
func (*EvidenceLink) Descriptor() ([]byte, []int) {
	return file_proto_v1_trace_proto_rawDescGZIP(), []int{5}
}

func (x *EvidenceLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *EvidenceLink) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *EvidenceLink) GetTraceNodeId() string {
	if x != nil {
		return x.TraceNodeId
	}
	return ""
}

func (x *EvidenceLink) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *EvidenceLink) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EvidenceLink) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EvidenceLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EvidenceLink) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EvidenceLink) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EvidenceLink) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EvidenceLink) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_trace_proto protoreflect.FileDescriptor

const file_proto_v1_trace_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/trace.proto\x12\x10phoenix.trace.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x04\n" +
	"\tTraceNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fsource_event\x18\x02 \x01(\tR\vsourceEvent\x12'\n" +
	"\x0fprocess_lineage\x18\x03 \x03(\tR\x0eprocessLineage\x12%\n" +
	"\x0etelemetry_refs\x18\x04 \x03(\tR\rtelemetryRefs\x12#\n" +
	"\revidence_refs\x18\x05 \x03(\tR\fevidenceRefs\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05trust\x18\a \x01(\x01R\x05trust\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\xd4\x03\n" +
	"\tTraceEdge\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\tR\x06edgeId\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\x12#\n" +
	"\rrelation_type\x18\x04 \x01(\tR\frelationType\x12'\n" +
	"\x0fcausal_strength\x18\x05 \x01(\x01R\x0ecausalStrength\x12\x1a\n" +
	"\bordering\x18\x06 \x01(\x04R\bordering\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xd3\x03\n" +
	"\fLineageGraph\x12\x19\n" +
	"\bgraph_id\x18\x01 \x01(\tR\agraphId\x121\n" +
	"\x05nodes\x18\x02 \x03(\v2\x1b.phoenix.trace.v1.TraceNodeR\x05nodes\x121\n" +
	"\x05edges\x18\x03 \x03(\v2\x1b.phoenix.trace.v1.TraceEdgeR\x05edges\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\tR\n" +
	"checkpoint\x12\x12\n" +
	"\x04root\x18\x05 \x01(\tR\x04root\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xa2\x03\n" +
	"\vCausalChain\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12#\n" +
	"\rordered_nodes\x18\x02 \x03(\tR\forderedNodes\x12!\n" +
	"\fparent_links\x18\x03 \x03(\tR\vparentLinks\x12'\n" +
	"\x0freplay_sequence\x18\x04 \x01(\x04R\x0ereplaySequence\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0fvalidation_hash\x18\n" +
	" \x01(\tR\x0evalidationHash\"\xbf\x03\n" +
	"\fProcessGraph\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\tR\x03pid\x12\x1d\n" +
	"\n" +
	"parent_pid\x18\x03 \x01(\tR\tparentPid\x12\x1d\n" +
	"\n" +
	"node_links\x18\x04 \x03(\tR\tnodeLinks\x12\x1c\n" +
	"\tlifecycle\x18\x05 \x01(\tR\tlifecycle\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xac\x03\n" +
	"\fEvidenceLink\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x1f\n" +
	"\vevidence_id\x18\x02 \x01(\tR\n" +
	"evidenceId\x12\"\n" +
	"\rtrace_node_id\x18\x03 \x01(\tR\vtraceNodeId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHashB5Z3github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/traceb\x06proto3"

var (
	file_proto_v1_trace_proto_rawDescOnce sync.Once
	file_proto_v1_trace_proto_rawDescData []byte
)

func file_proto_v1_trace_proto_rawDescGZIP() []byte {
	file_proto_v1_trace_proto_rawDescOnce.Do(func() {
		file_proto_v1_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_trace_proto_rawDesc), len(file_proto_v1_trace_proto_rawDesc)))
	})
	return file_proto_v1_trace_proto_rawDescData
}

var file_proto_v1_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_trace_proto_goTypes = []any{
	(*TraceNode)(nil),             // 0: phoenix.trace.v1.TraceNode
	(*TraceEdge)(nil),             // 1: phoenix.trace.v1.TraceEdge
	(*LineageGraph)(nil),          // 2: phoenix.trace.v1.LineageGraph
	(*CausalChain)(nil),           // 3: phoenix.trace.v1.CausalChain
	(*ProcessGraph)(nil),          // 4: phoenix.trace.v1.ProcessGraph
	(*EvidenceLink)(nil),          // 5: phoenix.trace.v1.EvidenceLink
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_trace_proto_depIdxs = []int32{
	6,  // 0: phoenix.trace.v1.TraceNode.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.trace.v1.TraceNode.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.trace.v1.TraceNode.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.trace.v1.TraceEdge.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: phoenix.trace.v1.TraceEdge.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: phoenix.trace.v1.LineageGraph.nodes:type_name -> phoenix.trace.v1.TraceNode
	1,  // 6: phoenix.trace.v1.LineageGraph.edges:type_name -> phoenix.trace.v1.TraceEdge
	6,  // 7: phoenix.trace.v1.LineageGraph.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.trace.v1.LineageGraph.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.trace.v1.CausalChain.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.trace.v1.CausalChain.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 11: phoenix.trace.v1.ProcessGraph.created_at:type_name -> google.protobuf.Timestamp
	6,  // 12: phoenix.trace.v1.ProcessGraph.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 13: phoenix.trace.v1.EvidenceLink.created_at:type_name -> google.protobuf.Timestamp
	6,  // 14: phoenix.trace.v1.EvidenceLink.updated_at:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_v1_trace_proto_init() }
func file_proto_v1_trace_proto_init() {
	if File_proto_v1_trace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_trace_proto_rawDesc), len(file_proto_v1_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_trace_proto_goTypes,
		DependencyIndexes: file_proto_v1_trace_proto_depIdxs,
		MessageInfos:      file_proto_v1_trace_proto_msgTypes,
	}.Build()
	File_proto_v1_trace_proto = out.File
	file_proto_v1_trace_proto_goTypes = nil
	file_proto_v1_trace_proto_depIdxs = nil
}
