/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Validation Protocol Definition — Replay Scenarios, Chaos Experiments, Invariant Checks
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/validation.proto

package validation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReplayScenario defines a deterministic replay test scenario.
type ReplayScenario struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId     string                 `protobuf:"bytes,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	Seed           string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Inputs         []string               `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	ExpectedState  string                 `protobuf:"bytes,4,opt,name=expected_state,json=expectedState,proto3" json:"expected_state,omitempty"`
	InvariantSet   []string               `protobuf:"bytes,5,rep,name=invariant_set,json=invariantSet,proto3" json:"invariant_set,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,6,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayScenario) Reset() {
	*x = ReplayScenario{}
	mi := &file_proto_v1_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayScenario) ProtoMessage() {}

func (x *ReplayScenario) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayScenario.ProtoReflect.Descriptor instead.
func (*ReplayScenario) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayScenario) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ReplayScenario) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *ReplayScenario) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ReplayScenario) GetExpectedState() string {
	if x != nil {
		return x.ExpectedState
	}
	return ""
}

func (x *ReplayScenario) GetInvariantSet() []string {
	if x != nil {
		return x.InvariantSet
	}
	return nil
}

func (x *ReplayScenario) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ReplayScenario) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ReplayScenario) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplayScenario) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReplayScenario) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ReplayScenario) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ReplayArtifact captures the inputs and outputs of a replay execution.
type ReplayArtifact struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	InputHash  string                 `protobuf:"bytes,2,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	OutputHash string                 `protobuf:"bytes,3,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"`
	Logs       []string               `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	Traces     []string               `protobuf:"bytes,5,rep,name=traces,proto3" json:"traces,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayArtifact) Reset() {
	*x = ReplayArtifact{}
	mi := &file_proto_v1_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayArtifact) ProtoMessage() {}

func (x *ReplayArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayArtifact.ProtoReflect.Descriptor instead.
func (*ReplayArtifact) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayArtifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ReplayArtifact) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *ReplayArtifact) GetOutputHash() string {
	if x != nil {
		return x.OutputHash
	}
	return ""
}

func (x *ReplayArtifact) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ReplayArtifact) GetTraces() []string {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *ReplayArtifact) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReplayArtifact) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ReplayArtifact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplayArtifact) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReplayArtifact) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ReplayArtifact) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ReplayArtifact) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ReplayResult records whether a replay scenario passed or failed.
type ReplayResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ResultId    string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	ScenarioId  string                 `protobuf:"bytes,2,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	PassFail    bool                   `protobuf:"varint,3,opt,name=pass_fail,json=passFail,proto3" json:"pass_fail,omitempty"`
	Divergence  string                 `protobuf:"bytes,4,opt,name=divergence,proto3" json:"divergence,omitempty"`
	Checksum    string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Remediation string                 `protobuf:"bytes,6,opt,name=remediation,proto3" json:"remediation,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayResult) Reset() {
	*x = ReplayResult{}
	mi := &file_proto_v1_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResult) ProtoMessage() {}

func (x *ReplayResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResult.ProtoReflect.Descriptor instead.
func (*ReplayResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{2}
}

func (x *ReplayResult) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *ReplayResult) GetScenarioId() string {
	if x != nil {
		return x.ScenarioId
	}
	return ""
}

func (x *ReplayResult) GetPassFail() bool {
	if x != nil {
		return x.PassFail
	}
	return false
}

func (x *ReplayResult) GetDivergence() string {
	if x != nil {
		return x.Divergence
	}
	return ""
}

func (x *ReplayResult) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ReplayResult) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *ReplayResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ReplayResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplayResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ReplayResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ReplayResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ReplayResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ChaosExperiment defines a controlled chaos testing scenario.
type ChaosExperiment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId       string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Scenario           string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	FaultInjections    []string               `protobuf:"bytes,3,rep,name=fault_injections,json=faultInjections,proto3" json:"fault_injections,omitempty"`
	Bounds             string                 `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	RecoveryConditions []string               `protobuf:"bytes,5,rep,name=recovery_conditions,json=recoveryConditions,proto3" json:"recovery_conditions,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChaosExperiment) Reset() {
	*x = ChaosExperiment{}
	mi := &file_proto_v1_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaosExperiment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaosExperiment) ProtoMessage() {}

func (x *ChaosExperiment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaosExperiment.ProtoReflect.Descriptor instead.
func (*ChaosExperiment) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ChaosExperiment) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ChaosExperiment) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *ChaosExperiment) GetFaultInjections() []string {
	if x != nil {
		return x.FaultInjections
	}
	return nil
}

func (x *ChaosExperiment) GetBounds() string {
	if x != nil {
		return x.Bounds
	}
	return ""
}

func (x *ChaosExperiment) GetRecoveryConditions() []string {
	if x != nil {
		return x.RecoveryConditions
	}
	return nil
}

func (x *ChaosExperiment) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ChaosExperiment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChaosExperiment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChaosExperiment) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ChaosExperiment) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ChaosExperiment) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// InvariantResult records the outcome of an invariant check.
type InvariantResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	InvariantId string                 `protobuf:"bytes,1,opt,name=invariant_id,json=invariantId,proto3" json:"invariant_id,omitempty"`
	Assertion   string                 `protobuf:"bytes,2,opt,name=assertion,proto3" json:"assertion,omitempty"`
	Observed    string                 `protobuf:"bytes,3,opt,name=observed,proto3" json:"observed,omitempty"`
	PassFail    bool                   `protobuf:"varint,4,opt,name=pass_fail,json=passFail,proto3" json:"pass_fail,omitempty"`
	Evidence    string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvariantResult) Reset() {
	*x = InvariantResult{}
	mi := &file_proto_v1_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvariantResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvariantResult) ProtoMessage() {}

func (x *InvariantResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvariantResult.ProtoReflect.Descriptor instead.
func (*InvariantResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{4}
}

func (x *InvariantResult) GetInvariantId() string {
	if x != nil {
		return x.InvariantId
	}
	return ""
}

func (x *InvariantResult) GetAssertion() string {
	if x != nil {
		return x.Assertion
	}
	return ""
}

func (x *InvariantResult) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

func (x *InvariantResult) GetPassFail() bool {
	if x != nil {
		return x.PassFail
	}
	return false
}

func (x *InvariantResult) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *InvariantResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *InvariantResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InvariantResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *InvariantResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *InvariantResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *InvariantResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ValidationReport is a comprehensive validation report covering all scenarios.
type ValidationReport struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ReportId    string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ScenarioIds []string               `protobuf:"bytes,2,rep,name=scenario_ids,json=scenarioIds,proto3" json:"scenario_ids,omitempty"`
	Results     []*ReplayResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Score       float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Regressions []string               `protobuf:"bytes,5,rep,name=regressions,proto3" json:"regressions,omitempty"`
	Signature   string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidationReport) Reset() {
	*x = ValidationReport{}
	mi := &file_proto_v1_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationReport) ProtoMessage() {}

func (x *ValidationReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationReport.ProtoReflect.Descriptor instead.
func (*ValidationReport) Descriptor() ([]byte, []int) {
	return file_proto_v1_validation_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ValidationReport) GetScenarioIds() []string {
	if x != nil {
		return x.ScenarioIds
	}
	return nil
}

func (x *ValidationReport) GetResults() []*ReplayResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ValidationReport) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ValidationReport) GetRegressions() []string {
	if x != nil {
		return x.Regressions
	}
	return nil
}

func (x *ValidationReport) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ValidationReport) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ValidationReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ValidationReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ValidationReport) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ValidationReport) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ValidationReport) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_validation_proto protoreflect.FileDescriptor

const file_proto_v1_validation_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v1/validation.proto\x12\x15phoenix.validation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x03\n" +
	"\x0eReplayScenario\x12\x1f\n" +
	"\vscenario_id\x18\x01 \x01(\tR\n" +
	"scenarioId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12\x16\n" +
	"\x06inputs\x18\x03 \x03(\tR\x06inputs\x12%\n" +
	"\x0eexpected_state\x18\x04 \x01(\tR\rexpectedState\x12#\n" +
	"\rinvariant_set\x18\x05 \x03(\tR\finvariantSet\x12'\n" +
	"\x0freplay_sequence\x18\x06 \x01(\x04R\x0ereplaySequence\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xe7\x03\n" +
	"\x0eReplayArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x02 \x01(\tR\tinputHash\x12\x1f\n" +
	"\voutput_hash\x18\x03 \x01(\tR\n" +
	"outputHash\x12\x12\n" +
	"\x04logs\x18\x04 \x03(\tR\x04logs\x12\x16\n" +
	"\x06traces\x18\x05 \x03(\tR\x06traces\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xd7\x03\n" +
	"\fReplayResult\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x1f\n" +
	"\vscenario_id\x18\x02 \x01(\tR\n" +
	"scenarioId\x12\x1b\n" +
	"\tpass_fail\x18\x03 \x01(\bR\bpassFail\x12\x1e\n" +
	"\n" +
	"divergence\x18\x04 \x01(\tR\n" +
	"divergence\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12 \n" +
	"\vremediation\x18\x06 \x01(\tR\vremediation\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xd6\x03\n" +
	"\x0fChaosExperiment\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12)\n" +
	"\x10fault_injections\x18\x03 \x03(\tR\x0ffaultInjections\x12\x16\n" +
	"\x06bounds\x18\x04 \x01(\tR\x06bounds\x12/\n" +
	"\x13recovery_conditions\x18\x05 \x03(\tR\x12recoveryConditions\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xb7\x03\n" +
	"\x0fInvariantResult\x12!\n" +
	"\finvariant_id\x18\x01 \x01(\tR\vinvariantId\x12\x1c\n" +
	"\tassertion\x18\x02 \x01(\tR\tassertion\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\tR\bobserved\x12\x1b\n" +
	"\tpass_fail\x18\x04 \x01(\bR\bpassFail\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xf7\x03\n" +
	"\x10ValidationReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12!\n" +
	"\fscenario_ids\x18\x02 \x03(\tR\vscenarioIds\x12=\n" +
	"\aresults\x18\x03 \x03(\v2#.phoenix.validation.v1.ReplayResultR\aresults\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12 \n" +
	"\vregressions\x18\x05 \x03(\tR\vregressions\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashB:Z8github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/validationb\x06proto3"

var (
	file_proto_v1_validation_proto_rawDescOnce sync.Once
	file_proto_v1_validation_proto_rawDescData []byte
)

func file_proto_v1_validation_proto_rawDescGZIP() []byte {
	file_proto_v1_validation_proto_rawDescOnce.Do(func() {
		file_proto_v1_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_validation_proto_rawDesc), len(file_proto_v1_validation_proto_rawDesc)))
	})
	return file_proto_v1_validation_proto_rawDescData
}

var file_proto_v1_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_validation_proto_goTypes = []any{
	(*ReplayScenario)(nil),        // 0: phoenix.validation.v1.ReplayScenario
	(*ReplayArtifact)(nil),        // 1: phoenix.validation.v1.ReplayArtifact
	(*ReplayResult)(nil),          // 2: phoenix.validation.v1.ReplayResult
	(*ChaosExperiment)(nil),       // 3: phoenix.validation.v1.ChaosExperiment
	(*InvariantResult)(nil),       // 4: phoenix.validation.v1.InvariantResult
	(*ValidationReport)(nil),      // 5: phoenix.validation.v1.ValidationReport
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_validation_proto_depIdxs = []int32{
	6,  // 0: phoenix.validation.v1.ReplayScenario.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.validation.v1.ReplayScenario.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.validation.v1.ReplayArtifact.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.validation.v1.ReplayArtifact.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: phoenix.validation.v1.ReplayArtifact.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: phoenix.validation.v1.ReplayResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: phoenix.validation.v1.ReplayResult.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: phoenix.validation.v1.ChaosExperiment.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.validation.v1.ChaosExperiment.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.validation.v1.InvariantResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.validation.v1.InvariantResult.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: phoenix.validation.v1.ValidationReport.results:type_name -> phoenix.validation.v1.ReplayResult
	6,  // 12: phoenix.validation.v1.ValidationReport.created_at:type_name -> google.protobuf.Timestamp
	6,  // 13: phoenix.validation.v1.ValidationReport.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_validation_proto_init() }
func file_proto_v1_validation_proto_init() {
	if File_proto_v1_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_validation_proto_rawDesc), len(file_proto_v1_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_validation_proto_goTypes,
		DependencyIndexes: file_proto_v1_validation_proto_depIdxs,
		MessageInfos:      file_proto_v1_validation_proto_msgTypes,
	}.Build()
	File_proto_v1_validation_proto = out.File
	file_proto_v1_validation_proto_goTypes = nil
	file_proto_v1_validation_proto_depIdxs = nil
}
