/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Advisory Protocol Definition — Advisory Envelopes, Recommendations, Evidence Bundles
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/advisory.proto

package advisory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Recommendation captures a specific advisory recommendation with impact analysis.
type Recommendation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Summary          string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Impact           string                 `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	Alternatives     []string               `protobuf:"bytes,5,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	OperatorAction   string                 `protobuf:"bytes,6,opt,name=operator_action,json=operatorAction,proto3" json:"operator_action,omitempty"`
	ConfidenceRef    string                 `protobuf:"bytes,7,opt,name=confidence_ref,json=confidenceRef,proto3" json:"confidence_ref,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_proto_v1_advisory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_advisory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_proto_v1_advisory_proto_rawDescGZIP(), []int{0}
}

func (x *Recommendation) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *Recommendation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Recommendation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Recommendation) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *Recommendation) GetAlternatives() []string {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *Recommendation) GetOperatorAction() string {
	if x != nil {
		return x.OperatorAction
	}
	return ""
}

func (x *Recommendation) GetConfidenceRef() string {
	if x != nil {
		return x.ConfidenceRef
	}
	return ""
}

func (x *Recommendation) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Recommendation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Recommendation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Recommendation) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *Recommendation) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *Recommendation) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// EvidenceBundle groups related evidence references for advisory decisions.
type EvidenceBundle struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BundleId     string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	EvidenceRefs []string               `protobuf:"bytes,2,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	LineageRefs  []string               `protobuf:"bytes,3,rep,name=lineage_refs,json=lineageRefs,proto3" json:"lineage_refs,omitempty"`
	TrustFloor   float64                `protobuf:"fixed64,4,opt,name=trust_floor,json=trustFloor,proto3" json:"trust_floor,omitempty"`
	Provenance   string                 `protobuf:"bytes,5,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Checksum     string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceBundle) Reset() {
	*x = EvidenceBundle{}
	mi := &file_proto_v1_advisory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceBundle) ProtoMessage() {}

func (x *EvidenceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_advisory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceBundle.ProtoReflect.Descriptor instead.
func (*EvidenceBundle) Descriptor() ([]byte, []int) {
	return file_proto_v1_advisory_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceBundle) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *EvidenceBundle) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *EvidenceBundle) GetLineageRefs() []string {
	if x != nil {
		return x.LineageRefs
	}
	return nil
}

func (x *EvidenceBundle) GetTrustFloor() float64 {
	if x != nil {
		return x.TrustFloor
	}
	return 0
}

func (x *EvidenceBundle) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *EvidenceBundle) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *EvidenceBundle) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EvidenceBundle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EvidenceBundle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EvidenceBundle) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EvidenceBundle) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EvidenceBundle) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// AdvisoryEnvelope is the canonical advisory message.
// Advisories are NEVER commands — they are bounded recommendations
// that require evidence and may require operator approval.
type AdvisoryEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdvisoryId       string                 `protobuf:"bytes,1,opt,name=advisory_id,json=advisoryId,proto3" json:"advisory_id,omitempty"`
	AdvisoryVersion  string                 `protobuf:"bytes,2,opt,name=advisory_version,json=advisoryVersion,proto3" json:"advisory_version,omitempty"`
	Recommendation   *Recommendation        `protobuf:"bytes,3,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	EvidenceBundle   *EvidenceBundle        `protobuf:"bytes,4,opt,name=evidence_bundle,json=evidenceBundle,proto3" json:"evidence_bundle,omitempty"`
	Confidence       float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskScore        float64                `protobuf:"fixed64,6,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	BoundedScope     string                 `protobuf:"bytes,7,opt,name=bounded_scope,json=boundedScope,proto3" json:"bounded_scope,omitempty"`
	Expiration       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
	ApprovalRequired bool                   `protobuf:"varint,9,opt,name=approval_required,json=approvalRequired,proto3" json:"approval_required,omitempty"`
	ForbiddenActions []string               `protobuf:"bytes,10,rep,name=forbidden_actions,json=forbiddenActions,proto3" json:"forbidden_actions,omitempty"`
	Signature        string                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,12,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,15,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,16,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,17,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdvisoryEnvelope) Reset() {
	*x = AdvisoryEnvelope{}
	mi := &file_proto_v1_advisory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisoryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisoryEnvelope) ProtoMessage() {}

func (x *AdvisoryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_advisory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisoryEnvelope.ProtoReflect.Descriptor instead.
func (*AdvisoryEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_v1_advisory_proto_rawDescGZIP(), []int{2}
}

func (x *AdvisoryEnvelope) GetAdvisoryId() string {
	if x != nil {
		return x.AdvisoryId
	}
	return ""
}

func (x *AdvisoryEnvelope) GetAdvisoryVersion() string {
	if x != nil {
		return x.AdvisoryVersion
	}
	return ""
}

func (x *AdvisoryEnvelope) GetRecommendation() *Recommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

func (x *AdvisoryEnvelope) GetEvidenceBundle() *EvidenceBundle {
	if x != nil {
		return x.EvidenceBundle
	}
	return nil
}

func (x *AdvisoryEnvelope) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AdvisoryEnvelope) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AdvisoryEnvelope) GetBoundedScope() string {
	if x != nil {
		return x.BoundedScope
	}
	return ""
}

func (x *AdvisoryEnvelope) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *AdvisoryEnvelope) GetApprovalRequired() bool {
	if x != nil {
		return x.ApprovalRequired
	}
	return false
}

func (x *AdvisoryEnvelope) GetForbiddenActions() []string {
	if x != nil {
		return x.ForbiddenActions
	}
	return nil
}

func (x *AdvisoryEnvelope) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AdvisoryEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AdvisoryEnvelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AdvisoryEnvelope) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AdvisoryEnvelope) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *AdvisoryEnvelope) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *AdvisoryEnvelope) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ConfidenceModel captures the statistical model behind an advisory's confidence score.
type ConfidenceModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Calibration   float64                `protobuf:"fixed64,3,opt,name=calibration,proto3" json:"calibration,omitempty"`
	Uncertainty   float64                `protobuf:"fixed64,4,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	SourceWeights []string               `protobuf:"bytes,6,rep,name=source_weights,json=sourceWeights,proto3" json:"source_weights,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfidenceModel) Reset() {
	*x = ConfidenceModel{}
	mi := &file_proto_v1_advisory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceModel) ProtoMessage() {}

func (x *ConfidenceModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_advisory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceModel.ProtoReflect.Descriptor instead.
func (*ConfidenceModel) Descriptor() ([]byte, []int) {
	return file_proto_v1_advisory_proto_rawDescGZIP(), []int{3}
}

func (x *ConfidenceModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ConfidenceModel) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ConfidenceModel) GetCalibration() float64 {
	if x != nil {
		return x.Calibration
	}
	return 0
}

func (x *ConfidenceModel) GetUncertainty() float64 {
	if x != nil {
		return x.Uncertainty
	}
	return 0
}

func (x *ConfidenceModel) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ConfidenceModel) GetSourceWeights() []string {
	if x != nil {
		return x.SourceWeights
	}
	return nil
}

func (x *ConfidenceModel) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ConfidenceModel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfidenceModel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfidenceModel) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ConfidenceModel) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ConfidenceModel) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ApprovalRequest is generated when an advisory requires human or elevated approval.
type ApprovalRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId     string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	AdvisoryId     string                 `protobuf:"bytes,2,opt,name=advisory_id,json=advisoryId,proto3" json:"advisory_id,omitempty"`
	RequestedBy    string                 `protobuf:"bytes,3,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	RequestedScope string                 `protobuf:"bytes,4,opt,name=requested_scope,json=requestedScope,proto3" json:"requested_scope,omitempty"`
	ApproverRole   string                 `protobuf:"bytes,5,opt,name=approver_role,json=approverRole,proto3" json:"approver_role,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RollbackPlan   string                 `protobuf:"bytes,7,opt,name=rollback_plan,json=rollbackPlan,proto3" json:"rollback_plan,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,11,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,12,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,13,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_proto_v1_advisory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_advisory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_advisory_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApprovalRequest) GetAdvisoryId() string {
	if x != nil {
		return x.AdvisoryId
	}
	return ""
}

func (x *ApprovalRequest) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *ApprovalRequest) GetRequestedScope() string {
	if x != nil {
		return x.RequestedScope
	}
	return ""
}

func (x *ApprovalRequest) GetApproverRole() string {
	if x != nil {
		return x.ApproverRole
	}
	return ""
}

func (x *ApprovalRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ApprovalRequest) GetRollbackPlan() string {
	if x != nil {
		return x.RollbackPlan
	}
	return ""
}

func (x *ApprovalRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ApprovalRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApprovalRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ApprovalRequest) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ApprovalRequest) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ApprovalRequest) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_advisory_proto protoreflect.FileDescriptor

const file_proto_v1_advisory_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/advisory.proto\x12\x13phoenix.advisory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x87\x04\n" +
	"\x0eRecommendation\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\tR\x06impact\x12\"\n" +
	"\falternatives\x18\x05 \x03(\tR\falternatives\x12'\n" +
	"\x0foperator_action\x18\x06 \x01(\tR\x0eoperatorAction\x12%\n" +
	"\x0econfidence_ref\x18\a \x01(\tR\rconfidenceRef\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHash\"\xe2\x03\n" +
	"\x0eEvidenceBundle\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12#\n" +
	"\revidence_refs\x18\x02 \x03(\tR\fevidenceRefs\x12!\n" +
	"\flineage_refs\x18\x03 \x03(\tR\vlineageRefs\x12\x1f\n" +
	"\vtrust_floor\x18\x04 \x01(\x01R\n" +
	"trustFloor\x12\x1e\n" +
	"\n" +
	"provenance\x18\x05 \x01(\tR\n" +
	"provenance\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xa1\x06\n" +
	"\x10AdvisoryEnvelope\x12\x1f\n" +
	"\vadvisory_id\x18\x01 \x01(\tR\n" +
	"advisoryId\x12)\n" +
	"\x10advisory_version\x18\x02 \x01(\tR\x0fadvisoryVersion\x12K\n" +
	"\x0erecommendation\x18\x03 \x01(\v2#.phoenix.advisory.v1.RecommendationR\x0erecommendation\x12L\n" +
	"\x0fevidence_bundle\x18\x04 \x01(\v2#.phoenix.advisory.v1.EvidenceBundleR\x0eevidenceBundle\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x06 \x01(\x01R\triskScore\x12#\n" +
	"\rbounded_scope\x18\a \x01(\tR\fboundedScope\x12:\n" +
	"\n" +
	"expiration\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12+\n" +
	"\x11approval_required\x18\t \x01(\bR\x10approvalRequired\x12+\n" +
	"\x11forbidden_actions\x18\n" +
	" \x03(\tR\x10forbiddenActions\x12\x1c\n" +
	"\tsignature\x18\v \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\f \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\x0f \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\x10 \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\x11 \x01(\tR\x0evalidationHash\"\xdf\x03\n" +
	"\x0fConfidenceModel\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12 \n" +
	"\vcalibration\x18\x03 \x01(\x01R\vcalibration\x12 \n" +
	"\vuncertainty\x18\x04 \x01(\x01R\vuncertainty\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12%\n" +
	"\x0esource_weights\x18\x06 \x03(\tR\rsourceWeights\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xae\x04\n" +
	"\x0fApprovalRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1f\n" +
	"\vadvisory_id\x18\x02 \x01(\tR\n" +
	"advisoryId\x12!\n" +
	"\frequested_by\x18\x03 \x01(\tR\vrequestedBy\x12'\n" +
	"\x0frequested_scope\x18\x04 \x01(\tR\x0erequestedScope\x12#\n" +
	"\rapprover_role\x18\x05 \x01(\tR\fapproverRole\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12#\n" +
	"\rrollback_plan\x18\a \x01(\tR\frollbackPlan\x12%\n" +
	"\x0eschema_version\x18\b \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\v \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\f \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\r \x01(\tR\x0evalidationHashB8Z6github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/advisoryb\x06proto3"

var (
	file_proto_v1_advisory_proto_rawDescOnce sync.Once
	file_proto_v1_advisory_proto_rawDescData []byte
)

func file_proto_v1_advisory_proto_rawDescGZIP() []byte {
	file_proto_v1_advisory_proto_rawDescOnce.Do(func() {
		file_proto_v1_advisory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_advisory_proto_rawDesc), len(file_proto_v1_advisory_proto_rawDesc)))
	})
	return file_proto_v1_advisory_proto_rawDescData
}

var file_proto_v1_advisory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_advisory_proto_goTypes = []any{
	(*Recommendation)(nil),        // 0: phoenix.advisory.v1.Recommendation
	(*EvidenceBundle)(nil),        // 1: phoenix.advisory.v1.EvidenceBundle
	(*AdvisoryEnvelope)(nil),      // 2: phoenix.advisory.v1.AdvisoryEnvelope
	(*ConfidenceModel)(nil),       // 3: phoenix.advisory.v1.ConfidenceModel
	(*ApprovalRequest)(nil),       // 4: phoenix.advisory.v1.ApprovalRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
}
var file_proto_v1_advisory_proto_depIdxs = []int32{
	5,  // 0: phoenix.advisory.v1.Recommendation.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: phoenix.advisory.v1.Recommendation.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: phoenix.advisory.v1.EvidenceBundle.created_at:type_name -> google.protobuf.Timestamp
	5,  // 3: phoenix.advisory.v1.EvidenceBundle.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: phoenix.advisory.v1.AdvisoryEnvelope.recommendation:type_name -> phoenix.advisory.v1.Recommendation
	1,  // 5: phoenix.advisory.v1.AdvisoryEnvelope.evidence_bundle:type_name -> phoenix.advisory.v1.EvidenceBundle
	5,  // 6: phoenix.advisory.v1.AdvisoryEnvelope.expiration:type_name -> google.protobuf.Timestamp
	5,  // 7: phoenix.advisory.v1.AdvisoryEnvelope.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: phoenix.advisory.v1.AdvisoryEnvelope.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 9: phoenix.advisory.v1.ConfidenceModel.created_at:type_name -> google.protobuf.Timestamp
	5,  // 10: phoenix.advisory.v1.ConfidenceModel.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 11: phoenix.advisory.v1.ApprovalRequest.timeout:type_name -> google.protobuf.Duration
	5,  // 12: phoenix.advisory.v1.ApprovalRequest.created_at:type_name -> google.protobuf.Timestamp
	5,  // 13: phoenix.advisory.v1.ApprovalRequest.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_v1_advisory_proto_init() }
func file_proto_v1_advisory_proto_init() {
	if File_proto_v1_advisory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_advisory_proto_rawDesc), len(file_proto_v1_advisory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_advisory_proto_goTypes,
		DependencyIndexes: file_proto_v1_advisory_proto_depIdxs,
		MessageInfos:      file_proto_v1_advisory_proto_msgTypes,
	}.Build()
	File_proto_v1_advisory_proto = out.File
	file_proto_v1_advisory_proto_goTypes = nil
	file_proto_v1_advisory_proto_depIdxs = nil
}
