/*
 * PHOENIX MATRIX SOVEREIGN ARCHITECTURE
 * [STATUS]: 18-Repository Substrate Consolidated
 * [FUTURE ENHANCEMENT]: Needs continuous formal verification scaling and HDF5 vector optimizations.
 * [POTENTIAL LOOPHOLE]: Ensure strict hardware isolation when deploying to bare-metal. Watch for timing side-channels.
 * [ERROR PRONE AREA]: Concurrency bottlenecks in event bus and race conditions in cross-domain memory mappings.
 */
// PhoenixCore — Canonical Contract System
// Memory Protocol Definition — Memory Records, Graphs, Semantic Links, Retrieval
// ALL repos depend on PhoenixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/memory.proto

package memory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemoryRecord represents a single memory entry in the system.
type MemoryRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RecordId    string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	MemoryType  string                 `protobuf:"bytes,2,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"`
	SourceEvent string                 `protobuf:"bytes,3,opt,name=source_event,json=sourceEvent,proto3" json:"source_event,omitempty"`
	ContentHash string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	TrustScore  float64                `protobuf:"fixed64,5,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	Retention   string                 `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_proto_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryRecord) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *MemoryRecord) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryRecord) GetSourceEvent() string {
	if x != nil {
		return x.SourceEvent
	}
	return ""
}

func (x *MemoryRecord) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *MemoryRecord) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *MemoryRecord) GetRetention() string {
	if x != nil {
		return x.Retention
	}
	return ""
}

func (x *MemoryRecord) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *MemoryRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MemoryRecord) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *MemoryRecord) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *MemoryRecord) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// MemoryChunk represents a fragment of a memory record for chunked storage.
type MemoryChunk struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChunkId            string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	RecordId           string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Sequence           uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SemanticVectorHash string                 `protobuf:"bytes,4,opt,name=semantic_vector_hash,json=semanticVectorHash,proto3" json:"semantic_vector_hash,omitempty"`
	Checksum           string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryChunk) Reset() {
	*x = MemoryChunk{}
	mi := &file_proto_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryChunk) ProtoMessage() {}

func (x *MemoryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryChunk.ProtoReflect.Descriptor instead.
func (*MemoryChunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *MemoryChunk) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *MemoryChunk) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MemoryChunk) GetSemanticVectorHash() string {
	if x != nil {
		return x.SemanticVectorHash
	}
	return ""
}

func (x *MemoryChunk) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *MemoryChunk) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *MemoryChunk) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryChunk) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MemoryChunk) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *MemoryChunk) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *MemoryChunk) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// SemanticLink represents a semantic relationship between two memory records.
type SemanticLink struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	LinkId     string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	FromRecord string                 `protobuf:"bytes,2,opt,name=from_record,json=fromRecord,proto3" json:"from_record,omitempty"`
	ToRecord   string                 `protobuf:"bytes,3,opt,name=to_record,json=toRecord,proto3" json:"to_record,omitempty"`
	Relation   string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Confidence float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SemanticLink) Reset() {
	*x = SemanticLink{}
	mi := &file_proto_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticLink) ProtoMessage() {}

func (x *SemanticLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticLink.ProtoReflect.Descriptor instead.
func (*SemanticLink) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *SemanticLink) GetFromRecord() string {
	if x != nil {
		return x.FromRecord
	}
	return ""
}

func (x *SemanticLink) GetToRecord() string {
	if x != nil {
		return x.ToRecord
	}
	return ""
}

func (x *SemanticLink) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *SemanticLink) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SemanticLink) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SemanticLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SemanticLink) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SemanticLink) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *SemanticLink) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *SemanticLink) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// MemoryGraph is the complete semantic memory graph.
type MemoryGraph struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GraphId    string                 `protobuf:"bytes,1,opt,name=graph_id,json=graphId,proto3" json:"graph_id,omitempty"`
	Nodes      []*MemoryRecord        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links      []*SemanticLink        `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Lineage    string                 `protobuf:"bytes,4,opt,name=lineage,proto3" json:"lineage,omitempty"`
	SnapshotId string                 `protobuf:"bytes,5,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryGraph) Reset() {
	*x = MemoryGraph{}
	mi := &file_proto_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryGraph) ProtoMessage() {}

func (x *MemoryGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryGraph.ProtoReflect.Descriptor instead.
func (*MemoryGraph) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryGraph) GetGraphId() string {
	if x != nil {
		return x.GraphId
	}
	return ""
}

func (x *MemoryGraph) GetNodes() []*MemoryRecord {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MemoryGraph) GetLinks() []*SemanticLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MemoryGraph) GetLineage() string {
	if x != nil {
		return x.Lineage
	}
	return ""
}

func (x *MemoryGraph) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *MemoryGraph) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *MemoryGraph) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryGraph) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MemoryGraph) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *MemoryGraph) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *MemoryGraph) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// RetrievalResult records the outcome of a memory retrieval query.
type RetrievalResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RetrievalId string                 `protobuf:"bytes,1,opt,name=retrieval_id,json=retrievalId,proto3" json:"retrieval_id,omitempty"`
	QueryHash   string                 `protobuf:"bytes,2,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
	Matches     []string               `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
	Ranking     []uint32               `protobuf:"varint,4,rep,packed,name=ranking,proto3" json:"ranking,omitempty"`
	Provenance  string                 `protobuf:"bytes,5,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Checksum    string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrievalResult) Reset() {
	*x = RetrievalResult{}
	mi := &file_proto_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalResult) ProtoMessage() {}

func (x *RetrievalResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalResult.ProtoReflect.Descriptor instead.
func (*RetrievalResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RetrievalResult) GetRetrievalId() string {
	if x != nil {
		return x.RetrievalId
	}
	return ""
}

func (x *RetrievalResult) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

func (x *RetrievalResult) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *RetrievalResult) GetRanking() []uint32 {
	if x != nil {
		return x.Ranking
	}
	return nil
}

func (x *RetrievalResult) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *RetrievalResult) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *RetrievalResult) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RetrievalResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RetrievalResult) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RetrievalResult) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *RetrievalResult) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *RetrievalResult) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// MemorySnapshot captures the full state of the memory system at an epoch.
type MemorySnapshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Epoch      uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Records    []*MemoryRecord        `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	GraphRoot  string                 `protobuf:"bytes,4,opt,name=graph_root,json=graphRoot,proto3" json:"graph_root,omitempty"`
	Signature  string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,9,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,10,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,11,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemorySnapshot) Reset() {
	*x = MemorySnapshot{}
	mi := &file_proto_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySnapshot) ProtoMessage() {}

func (x *MemorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySnapshot.ProtoReflect.Descriptor instead.
func (*MemorySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *MemorySnapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *MemorySnapshot) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MemorySnapshot) GetRecords() []*MemoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *MemorySnapshot) GetGraphRoot() string {
	if x != nil {
		return x.GraphRoot
	}
	return ""
}

func (x *MemorySnapshot) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MemorySnapshot) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *MemorySnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemorySnapshot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *MemorySnapshot) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *MemorySnapshot) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *MemorySnapshot) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_memory_proto protoreflect.FileDescriptor

const file_proto_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/memory.proto\x12\x11phoenix.memory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x03\n" +
	"\fMemoryRecord\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1f\n" +
	"\vmemory_type\x18\x02 \x01(\tR\n" +
	"memoryType\x12!\n" +
	"\fsource_event\x18\x03 \x01(\tR\vsourceEvent\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vtrust_score\x18\x05 \x01(\x01R\n" +
	"trustScore\x12\x1c\n" +
	"\tretention\x18\x06 \x01(\tR\tretention\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xbf\x03\n" +
	"\vMemoryChunk\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x120\n" +
	"\x14semantic_vector_hash\x18\x04 \x01(\tR\x12semanticVectorHash\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xb1\x03\n" +
	"\fSemanticLink\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x1f\n" +
	"\vfrom_record\x18\x02 \x01(\tR\n" +
	"fromRecord\x12\x1b\n" +
	"\tto_record\x18\x03 \x01(\tR\btoRecord\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xe1\x03\n" +
	"\vMemoryGraph\x12\x19\n" +
	"\bgraph_id\x18\x01 \x01(\tR\agraphId\x125\n" +
	"\x05nodes\x18\x02 \x03(\v2\x1f.phoenix.memory.v1.MemoryRecordR\x05nodes\x125\n" +
	"\x05links\x18\x03 \x03(\v2\x1f.phoenix.memory.v1.SemanticLinkR\x05links\x12\x18\n" +
	"\alineage\x18\x04 \x01(\tR\alineage\x12\x1f\n" +
	"\vsnapshot_id\x18\x05 \x01(\tR\n" +
	"snapshotId\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHash\"\xd3\x03\n" +
	"\x0fRetrievalResult\x12!\n" +
	"\fretrieval_id\x18\x01 \x01(\tR\vretrievalId\x12\x1d\n" +
	"\n" +
	"query_hash\x18\x02 \x01(\tR\tqueryHash\x12\x18\n" +
	"\amatches\x18\x03 \x03(\tR\amatches\x12\x18\n" +
	"\aranking\x18\x04 \x03(\rR\aranking\x12\x1e\n" +
	"\n" +
	"provenance\x18\x05 \x01(\tR\n" +
	"provenance\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xcf\x03\n" +
	"\x0eMemorySnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x129\n" +
	"\arecords\x18\x03 \x03(\v2\x1f.phoenix.memory.v1.MemoryRecordR\arecords\x12\x1d\n" +
	"\n" +
	"graph_root\x18\x04 \x01(\tR\tgraphRoot\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\t \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\n" +
	" \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\v \x01(\tR\x0evalidationHashB6Z4github.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/memoryb\x06proto3"

var (
	file_proto_v1_memory_proto_rawDescOnce sync.Once
	file_proto_v1_memory_proto_rawDescData []byte
)

func file_proto_v1_memory_proto_rawDescGZIP() []byte {
	file_proto_v1_memory_proto_rawDescOnce.Do(func() {
		file_proto_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_memory_proto_rawDesc), len(file_proto_v1_memory_proto_rawDesc)))
	})
	return file_proto_v1_memory_proto_rawDescData
}

var file_proto_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_memory_proto_goTypes = []any{
	(*MemoryRecord)(nil),          // 0: phoenix.memory.v1.MemoryRecord
	(*MemoryChunk)(nil),           // 1: phoenix.memory.v1.MemoryChunk
	(*SemanticLink)(nil),          // 2: phoenix.memory.v1.SemanticLink
	(*MemoryGraph)(nil),           // 3: phoenix.memory.v1.MemoryGraph
	(*RetrievalResult)(nil),       // 4: phoenix.memory.v1.RetrievalResult
	(*MemorySnapshot)(nil),        // 5: phoenix.memory.v1.MemorySnapshot
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_memory_proto_depIdxs = []int32{
	6,  // 0: phoenix.memory.v1.MemoryRecord.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.memory.v1.MemoryRecord.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.memory.v1.MemoryChunk.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.memory.v1.MemoryChunk.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 4: phoenix.memory.v1.SemanticLink.created_at:type_name -> google.protobuf.Timestamp
	6,  // 5: phoenix.memory.v1.SemanticLink.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: phoenix.memory.v1.MemoryGraph.nodes:type_name -> phoenix.memory.v1.MemoryRecord
	2,  // 7: phoenix.memory.v1.MemoryGraph.links:type_name -> phoenix.memory.v1.SemanticLink
	6,  // 8: phoenix.memory.v1.MemoryGraph.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.memory.v1.MemoryGraph.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.memory.v1.RetrievalResult.created_at:type_name -> google.protobuf.Timestamp
	6,  // 11: phoenix.memory.v1.RetrievalResult.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 12: phoenix.memory.v1.MemorySnapshot.records:type_name -> phoenix.memory.v1.MemoryRecord
	6,  // 13: phoenix.memory.v1.MemorySnapshot.created_at:type_name -> google.protobuf.Timestamp
	6,  // 14: phoenix.memory.v1.MemorySnapshot.updated_at:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_v1_memory_proto_init() }
func file_proto_v1_memory_proto_init() {
	if File_proto_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_memory_proto_rawDesc), len(file_proto_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_memory_proto_goTypes,
		DependencyIndexes: file_proto_v1_memory_proto_depIdxs,
		MessageInfos:      file_proto_v1_memory_proto_msgTypes,
	}.Build()
	File_proto_v1_memory_proto = out.File
	file_proto_v1_memory_proto_goTypes = nil
	file_proto_v1_memory_proto_depIdxs = nil
}
