// PheonixCore — Canonical Contract System
// Truth Protocol Definition — Evidence Assessment, Contradictions, Truth Reports
// ALL repos depend on PheonixCore contracts. NO other repo may export cross-boundary types.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/v1/truth.proto

package truth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Evidence represents a single piece of verified evidence.
type Evidence struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EvidenceId   string                 `protobuf:"bytes,1,opt,name=evidence_id,json=evidenceId,proto3" json:"evidence_id,omitempty"`
	EvidenceHash string                 `protobuf:"bytes,2,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	Source       string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	PayloadRef   string                 `protobuf:"bytes,4,opt,name=payload_ref,json=payloadRef,proto3" json:"payload_ref,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TrustFloor   float64                `protobuf:"fixed64,6,opt,name=trust_floor,json=trustFloor,proto3" json:"trust_floor,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_proto_v1_truth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{0}
}

func (x *Evidence) GetEvidenceId() string {
	if x != nil {
		return x.EvidenceId
	}
	return ""
}

func (x *Evidence) GetEvidenceHash() string {
	if x != nil {
		return x.EvidenceHash
	}
	return ""
}

func (x *Evidence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Evidence) GetPayloadRef() string {
	if x != nil {
		return x.PayloadRef
	}
	return ""
}

func (x *Evidence) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Evidence) GetTrustFloor() float64 {
	if x != nil {
		return x.TrustFloor
	}
	return 0
}

func (x *Evidence) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Evidence) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Evidence) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Evidence) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *Evidence) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *Evidence) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// EvidenceSource identifies the origin and authority level of evidence.
type EvidenceSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceId       string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Repo           string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Component      string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	AuthorityLevel string                 `protobuf:"bytes,4,opt,name=authority_level,json=authorityLevel,proto3" json:"authority_level,omitempty"`
	SignatureKey   string                 `protobuf:"bytes,5,opt,name=signature_key,json=signatureKey,proto3" json:"signature_key,omitempty"`
	Ranking        uint32                 `protobuf:"varint,6,opt,name=ranking,proto3" json:"ranking,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvidenceSource) Reset() {
	*x = EvidenceSource{}
	mi := &file_proto_v1_truth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceSource) ProtoMessage() {}

func (x *EvidenceSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceSource.ProtoReflect.Descriptor instead.
func (*EvidenceSource) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceSource) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *EvidenceSource) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *EvidenceSource) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *EvidenceSource) GetAuthorityLevel() string {
	if x != nil {
		return x.AuthorityLevel
	}
	return ""
}

func (x *EvidenceSource) GetSignatureKey() string {
	if x != nil {
		return x.SignatureKey
	}
	return ""
}

func (x *EvidenceSource) GetRanking() uint32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *EvidenceSource) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *EvidenceSource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EvidenceSource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EvidenceSource) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *EvidenceSource) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *EvidenceSource) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// TruthAssessment is the system's conclusion about a set of evidence.
type TruthAssessment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId      string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	EvidenceIds       []string               `protobuf:"bytes,2,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	Conclusion        string                 `protobuf:"bytes,3,opt,name=conclusion,proto3" json:"conclusion,omitempty"`
	Confidence        float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ContradictionRefs []string               `protobuf:"bytes,5,rep,name=contradiction_refs,json=contradictionRefs,proto3" json:"contradiction_refs,omitempty"`
	Rationale         string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TruthAssessment) Reset() {
	*x = TruthAssessment{}
	mi := &file_proto_v1_truth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruthAssessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruthAssessment) ProtoMessage() {}

func (x *TruthAssessment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruthAssessment.ProtoReflect.Descriptor instead.
func (*TruthAssessment) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{2}
}

func (x *TruthAssessment) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *TruthAssessment) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *TruthAssessment) GetConclusion() string {
	if x != nil {
		return x.Conclusion
	}
	return ""
}

func (x *TruthAssessment) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TruthAssessment) GetContradictionRefs() []string {
	if x != nil {
		return x.ContradictionRefs
	}
	return nil
}

func (x *TruthAssessment) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *TruthAssessment) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TruthAssessment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TruthAssessment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TruthAssessment) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *TruthAssessment) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *TruthAssessment) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// ConfidenceAssessment provides detailed confidence scoring with calibration.
type ConfidenceAssessment struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ConfidenceId string                 `protobuf:"bytes,1,opt,name=confidence_id,json=confidenceId,proto3" json:"confidence_id,omitempty"`
	Score        float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Weights      []float64              `protobuf:"fixed64,3,rep,packed,name=weights,proto3" json:"weights,omitempty"`
	Calibration  float64                `protobuf:"fixed64,4,opt,name=calibration,proto3" json:"calibration,omitempty"`
	Uncertainty  float64                `protobuf:"fixed64,5,opt,name=uncertainty,proto3" json:"uncertainty,omitempty"`
	Explanation  string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfidenceAssessment) Reset() {
	*x = ConfidenceAssessment{}
	mi := &file_proto_v1_truth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceAssessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceAssessment) ProtoMessage() {}

func (x *ConfidenceAssessment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceAssessment.ProtoReflect.Descriptor instead.
func (*ConfidenceAssessment) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{3}
}

func (x *ConfidenceAssessment) GetConfidenceId() string {
	if x != nil {
		return x.ConfidenceId
	}
	return ""
}

func (x *ConfidenceAssessment) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ConfidenceAssessment) GetWeights() []float64 {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *ConfidenceAssessment) GetCalibration() float64 {
	if x != nil {
		return x.Calibration
	}
	return 0
}

func (x *ConfidenceAssessment) GetUncertainty() float64 {
	if x != nil {
		return x.Uncertainty
	}
	return 0
}

func (x *ConfidenceAssessment) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *ConfidenceAssessment) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *ConfidenceAssessment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConfidenceAssessment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ConfidenceAssessment) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *ConfidenceAssessment) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *ConfidenceAssessment) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// Contradiction records when two pieces of evidence conflict.
type Contradiction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContradictionId string                 `protobuf:"bytes,1,opt,name=contradiction_id,json=contradictionId,proto3" json:"contradiction_id,omitempty"`
	EvidenceA       string                 `protobuf:"bytes,2,opt,name=evidence_a,json=evidenceA,proto3" json:"evidence_a,omitempty"`
	EvidenceB       string                 `protobuf:"bytes,3,opt,name=evidence_b,json=evidenceB,proto3" json:"evidence_b,omitempty"`
	Severity        string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Resolution      string                 `protobuf:"bytes,5,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Detector        string                 `protobuf:"bytes,6,opt,name=detector,proto3" json:"detector,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Contradiction) Reset() {
	*x = Contradiction{}
	mi := &file_proto_v1_truth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contradiction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contradiction) ProtoMessage() {}

func (x *Contradiction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contradiction.ProtoReflect.Descriptor instead.
func (*Contradiction) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{4}
}

func (x *Contradiction) GetContradictionId() string {
	if x != nil {
		return x.ContradictionId
	}
	return ""
}

func (x *Contradiction) GetEvidenceA() string {
	if x != nil {
		return x.EvidenceA
	}
	return ""
}

func (x *Contradiction) GetEvidenceB() string {
	if x != nil {
		return x.EvidenceB
	}
	return ""
}

func (x *Contradiction) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Contradiction) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *Contradiction) GetDetector() string {
	if x != nil {
		return x.Detector
	}
	return ""
}

func (x *Contradiction) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Contradiction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contradiction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Contradiction) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *Contradiction) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *Contradiction) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

// TruthReport is a comprehensive truth assessment report.
type TruthReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReportId          string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	Assessments       []*TruthAssessment     `protobuf:"bytes,2,rep,name=assessments,proto3" json:"assessments,omitempty"`
	Contradictions    []*Contradiction       `protobuf:"bytes,3,rep,name=contradictions,proto3" json:"contradictions,omitempty"`
	ConfidenceSummary string                 `protobuf:"bytes,4,opt,name=confidence_summary,json=confidenceSummary,proto3" json:"confidence_summary,omitempty"`
	Signature         string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// --- Mandatory canonical fields ---
	SchemaVersion  string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceRepo     string                 `protobuf:"bytes,10,opt,name=source_repo,json=sourceRepo,proto3" json:"source_repo,omitempty"`
	ReplaySequence uint64                 `protobuf:"varint,11,opt,name=replay_sequence,json=replaySequence,proto3" json:"replay_sequence,omitempty"`
	ValidationHash string                 `protobuf:"bytes,12,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TruthReport) Reset() {
	*x = TruthReport{}
	mi := &file_proto_v1_truth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruthReport) ProtoMessage() {}

func (x *TruthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_truth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruthReport.ProtoReflect.Descriptor instead.
func (*TruthReport) Descriptor() ([]byte, []int) {
	return file_proto_v1_truth_proto_rawDescGZIP(), []int{5}
}

func (x *TruthReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *TruthReport) GetAssessments() []*TruthAssessment {
	if x != nil {
		return x.Assessments
	}
	return nil
}

func (x *TruthReport) GetContradictions() []*Contradiction {
	if x != nil {
		return x.Contradictions
	}
	return nil
}

func (x *TruthReport) GetConfidenceSummary() string {
	if x != nil {
		return x.ConfidenceSummary
	}
	return ""
}

func (x *TruthReport) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TruthReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TruthReport) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TruthReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TruthReport) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *TruthReport) GetSourceRepo() string {
	if x != nil {
		return x.SourceRepo
	}
	return ""
}

func (x *TruthReport) GetReplaySequence() uint64 {
	if x != nil {
		return x.ReplaySequence
	}
	return 0
}

func (x *TruthReport) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

var File_proto_v1_truth_proto protoreflect.FileDescriptor

const file_proto_v1_truth_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/truth.proto\x12\x10phoenix.truth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x03\n" +
	"\bEvidence\x12\x1f\n" +
	"\vevidence_id\x18\x01 \x01(\tR\n" +
	"evidenceId\x12#\n" +
	"\revidence_hash\x18\x02 \x01(\tR\fevidenceHash\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vpayload_ref\x18\x04 \x01(\tR\n" +
	"payloadRef\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vtrust_floor\x18\x06 \x01(\x01R\n" +
	"trustFloor\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xd7\x03\n" +
	"\x0eEvidenceSource\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12'\n" +
	"\x0fauthority_level\x18\x04 \x01(\tR\x0eauthorityLevel\x12#\n" +
	"\rsignature_key\x18\x05 \x01(\tR\fsignatureKey\x12\x18\n" +
	"\aranking\x18\x06 \x01(\rR\aranking\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xf6\x03\n" +
	"\x0fTruthAssessment\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12!\n" +
	"\fevidence_ids\x18\x02 \x03(\tR\vevidenceIds\x12\x1e\n" +
	"\n" +
	"conclusion\x18\x03 \x01(\tR\n" +
	"conclusion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12-\n" +
	"\x12contradiction_refs\x18\x05 \x03(\tR\x11contradictionRefs\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xe1\x03\n" +
	"\x14ConfidenceAssessment\x12#\n" +
	"\rconfidence_id\x18\x01 \x01(\tR\fconfidenceId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x18\n" +
	"\aweights\x18\x03 \x03(\x01R\aweights\x12 \n" +
	"\vcalibration\x18\x04 \x01(\x01R\vcalibration\x12 \n" +
	"\vuncertainty\x18\x05 \x01(\x01R\vuncertainty\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xe0\x03\n" +
	"\rContradiction\x12)\n" +
	"\x10contradiction_id\x18\x01 \x01(\tR\x0fcontradictionId\x12\x1d\n" +
	"\n" +
	"evidence_a\x18\x02 \x01(\tR\tevidenceA\x12\x1d\n" +
	"\n" +
	"evidence_b\x18\x03 \x01(\tR\tevidenceB\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1e\n" +
	"\n" +
	"resolution\x18\x05 \x01(\tR\n" +
	"resolution\x12\x1a\n" +
	"\bdetector\x18\x06 \x01(\tR\bdetector\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHash\"\xaf\x04\n" +
	"\vTruthReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12C\n" +
	"\vassessments\x18\x02 \x03(\v2!.phoenix.truth.v1.TruthAssessmentR\vassessments\x12G\n" +
	"\x0econtradictions\x18\x03 \x03(\v2\x1f.phoenix.truth.v1.ContradictionR\x0econtradictions\x12-\n" +
	"\x12confidence_summary\x18\x04 \x01(\tR\x11confidenceSummary\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vsource_repo\x18\n" +
	" \x01(\tR\n" +
	"sourceRepo\x12'\n" +
	"\x0freplay_sequence\x18\v \x01(\x04R\x0ereplaySequence\x12'\n" +
	"\x0fvalidation_hash\x18\f \x01(\tR\x0evalidationHashBDZBgithub.com/fallofpheonix/phoenix/foundation/runtime/proto/v1/truthb\x06proto3"

var (
	file_proto_v1_truth_proto_rawDescOnce sync.Once
	file_proto_v1_truth_proto_rawDescData []byte
)

func file_proto_v1_truth_proto_rawDescGZIP() []byte {
	file_proto_v1_truth_proto_rawDescOnce.Do(func() {
		file_proto_v1_truth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_truth_proto_rawDesc), len(file_proto_v1_truth_proto_rawDesc)))
	})
	return file_proto_v1_truth_proto_rawDescData
}

var file_proto_v1_truth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_truth_proto_goTypes = []any{
	(*Evidence)(nil),              // 0: phoenix.truth.v1.Evidence
	(*EvidenceSource)(nil),        // 1: phoenix.truth.v1.EvidenceSource
	(*TruthAssessment)(nil),       // 2: phoenix.truth.v1.TruthAssessment
	(*ConfidenceAssessment)(nil),  // 3: phoenix.truth.v1.ConfidenceAssessment
	(*Contradiction)(nil),         // 4: phoenix.truth.v1.Contradiction
	(*TruthReport)(nil),           // 5: phoenix.truth.v1.TruthReport
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_v1_truth_proto_depIdxs = []int32{
	6,  // 0: phoenix.truth.v1.Evidence.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 1: phoenix.truth.v1.Evidence.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: phoenix.truth.v1.Evidence.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 3: phoenix.truth.v1.EvidenceSource.created_at:type_name -> google.protobuf.Timestamp
	6,  // 4: phoenix.truth.v1.EvidenceSource.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: phoenix.truth.v1.TruthAssessment.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: phoenix.truth.v1.TruthAssessment.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: phoenix.truth.v1.ConfidenceAssessment.created_at:type_name -> google.protobuf.Timestamp
	6,  // 8: phoenix.truth.v1.ConfidenceAssessment.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 9: phoenix.truth.v1.Contradiction.created_at:type_name -> google.protobuf.Timestamp
	6,  // 10: phoenix.truth.v1.Contradiction.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: phoenix.truth.v1.TruthReport.assessments:type_name -> phoenix.truth.v1.TruthAssessment
	4,  // 12: phoenix.truth.v1.TruthReport.contradictions:type_name -> phoenix.truth.v1.Contradiction
	6,  // 13: phoenix.truth.v1.TruthReport.created_at:type_name -> google.protobuf.Timestamp
	6,  // 14: phoenix.truth.v1.TruthReport.updated_at:type_name -> google.protobuf.Timestamp
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_v1_truth_proto_init() }
func file_proto_v1_truth_proto_init() {
	if File_proto_v1_truth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_truth_proto_rawDesc), len(file_proto_v1_truth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_truth_proto_goTypes,
		DependencyIndexes: file_proto_v1_truth_proto_depIdxs,
		MessageInfos:      file_proto_v1_truth_proto_msgTypes,
	}.Build()
	File_proto_v1_truth_proto = out.File
	file_proto_v1_truth_proto_goTypes = nil
	file_proto_v1_truth_proto_depIdxs = nil
}
