import subprocess
import time

# Define the 21 stages from LONG_TERM_STRUCTURE.md
stages = [
    ("Stage 00", "Foundations", "01_research/stage_00_foundations"),
    ("Stage 01", "System Internals", "01_research/stage_01_system_internals"),
    ("Stage 02", "Linux and Distros", "01_research/stage_02_linux_and_distros"),
    ("Stage 03", "Networking", "01_research/stage_03_networking"),
    ("Stage 04", "Security", "01_research/stage_04_security"),
    ("Stage 05", "Reverse Engineering", "01_research/stage_05_reverse_engineering"),
    ("Stage 06", "Forensics", "01_research/stage_06_forensics"),
    ("Stage 07", "Threat Intelligence", "01_research/stage_07_threat_intelligence"),
    ("Stage 08", "Observability", "01_research/stage_08_observability"),
    ("Stage 09", "Telemetry", "01_research/stage_09_telemetry"),
    ("Stage 10", "SOC", "01_research/stage_10_soc"),
    ("Stage 11", "AI/ML", "01_research/stage_11_ai_ml"),
    ("Stage 12", "Security AI", "01_research/stage_12_security_ai"),
    ("Stage 13", "Cloud", "01_research/stage_13_cloud"),
    ("Stage 14", "Automation", "01_research/stage_14_automation"),
    ("Stage 15", "Security Distribution", "01_research/stage_15_security_distribution"),
    ("Stage 16", "Kernel Extensions", "01_research/stage_16_kernel_extensions"),
    ("Stage 17", "Hybrid OS", "01_research/stage_17_hybrid_os"),
    ("Stage 18", "Custom OS", "01_research/stage_18_custom_os"),
    ("Stage 19", "Production", "01_research/stage_19_production"),
    ("Stage 20", "Future", "01_research/stage_20_future"),
]

task_templates = [
    "Research and document theoretical foundations for {topic}",
    "Implement initial prototypes for {topic} components",
    "Integrate {topic} telemetry into PhoenixOS event bus",
    "Define threat models and test cases for {topic}",
    "Perform load testing and benchmarking on {topic} modules"
]

labels_map = {
    "Research and document": "research,needs-triage",
    "Implement initial prototypes": "enhancement,needs-triage",
    "Integrate": "integration,needs-triage",
    "Define threat models": "security,needs-triage",
    "Perform load testing": "testing,needs-triage"
}

issues_created = 0

print("Generating and creating 105 structural issues based on LONG_TERM_STRUCTURE.md...")

for stage_id, topic, path in stages:
    for template in task_templates:
        title = f"[{stage_id}] {template.format(topic=topic)}"
        body = f"""> *This was generated by AI during triage.*

## Description
This is a planned milestone for **{stage_id}: {topic}** as defined in the `LONG_TERM_STRUCTURE.md`.

## Execution Path
- **Target Subsystem:** `{path}`
- **Goal:** Fulfill the requirements for {topic} within the PhoenixOS roadmap.

## Acceptance Criteria
- [ ] Complete prerequisite research.
- [ ] Implement core logic.
- [ ] Pass corresponding `devctl` lifecycle gates.
"""
        
        # Determine label based on prefix
        label = "needs-triage"
        for prefix, lbl in labels_map.items():
            if title.startswith(f"[{stage_id}] {prefix}"):
                label = lbl
                break
        
        # Execute gh issue create
        cmd = [
            "gh", "issue", "create",
            "--title", title,
            "--body", body,
            "--label", label
        ]
        
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            issues_created += 1
            print(f"Created issue {issues_created}/105: {title}")
            time.sleep(2)  # Delay to prevent rate limiting
        except subprocess.CalledProcessError as e:
            print(f"Failed to create issue: {title}")
            print(f"Error: {e.stderr}")
            # If we hit a rate limit or error, back off
            time.sleep(10)

print(f"Successfully created {issues_created} issues on GitHub.")
