import subprocess
import time

issues = [
    ("[LABS] [L0] Implement Foundations Labs", "Implement labs 00-08 defined in 01_research/stage_00_foundations/labs/phase_00_implementation_labs.md.\n\nTasks:\n- Lab 00: Number systems\n- Lab 01: Memory model\n- Lab 02: Sequential data structures\n- Lab 08: Problem-solving", "enhancement,needs-triage"),
    ("[LABS] [L0] Implement Architecture Labs", "Implement labs defined in 01_research/stage_00_foundations/labs/phase_01_architecture_labs.md.\n\nTasks:\n- Assembly calling convention\n- Cache locality benchmark\n- False sharing analysis", "enhancement,needs-triage"),
    ("[LABS] [L0] Implement Programming Labs", "Implement labs defined in 01_research/stage_00_foundations/labs/phase_02_low_level_programming_labs.md.\n\nTasks:\n- Heap allocator\n- ELF parser\n- Mini shell", "enhancement,needs-triage"),
    ("[LABS] [L1] Implement OS Internals Labs", "Implement labs defined in 01_research/stage_01_system_internals/labs/phase_03_operating_systems_labs.md.\n\nTasks:\n- Process lifecycle\n- Scheduler\n- VFS", "enhancement,needs-triage"),
    ("[LABS] [L2] Implement Linux Internals Labs", "Implement labs defined in 01_research/stage_02_linux_and_distros/labs/phase_04_linux_internals_labs.md.\n\nTasks:\n- Kernel build\n- Kernel module\n- Namespaces/cgroups", "enhancement,needs-triage"),
    ("[LABS] [L3] Implement Networking Labs", "Implement labs defined in 01_research/stage_03_networking/labs/phase_05_networking_labs.md.\n\nTasks:\n- OSI/Encapsulation\n- DNS\n- TCP\n- Packet dissection", "enhancement,needs-triage"),
    ("[SURFACE] Refactor Orchestrator State Handling", "The file agents/surface/orchestrator/service.py contains TODOs related to label management ('surface:todo').\n\nTasks:\n- Refactor state-to-label mapping.\n- Replace hardcoded TODO labels.", "bug,needs-triage"),
    ("[L0] Foundations: Establish Problem-solving Lab Set", "Per 01_research/stage_00_foundations/labs/phase_00_implementation_labs.md, the Problem-solving lab (Lab 08) needs definition.\n\nTasks:\n- Define the lab requirements for the problem-solving set.", "research,needs-triage"),
    ("[L1] Architecture: Document NUMA Topology Reasoning", "Document topology and locality rationale for PhoenixOS (01_research/stage_00_foundations/labs/phase_01_architecture_labs.md).", "documentation,needs-triage"),
    ("[L1] Low-Level Programming: Formalize Rust Syscall Wrapper", "Design safe syscall abstraction layer for Rust (01_research/stage_00_foundations/labs/phase_02_low_level_programming_labs.md).", "enhancement,needs-triage"),
    ("[L2] OS Internals: Modify xv6 for PhoenixOS", "Plan modifications for syscalls, scheduler, and file operations in xv6 (01_research/stage_01_system_internals/labs/phase_03_operating_systems_labs.md).", "research,needs-triage"),
    ("[L3] Networking: Implement Packet Dissection Parser", "Implement hex parsing for raw packets (01_research/stage_03_networking/labs/phase_05_networking_labs.md).", "enhancement,needs-triage"),
    ("[SURFACE] Orchestrator: Update Label Management", "Update labels from 'surface:todo' to canonical triage labels in agents/surface/orchestrator/service.py.", "bug,needs-triage"),
    ("[LABS] [L2] cgroups: Investigate v1 vs v2 differences", "Analyze differences between cgroup v1 and v2 (01_research/stage_02_linux_and_distros/labs/phase_04_linux_internals_labs.md).", "research,needs-triage"),
    ("[LABS] [L3] Networking: Security Analysis of DNS Exfiltration", "Perform security analysis on plaintext DNS vs. DoH (01_research/stage_03_networking/labs/phase_05_networking_labs.md).", "security,needs-triage")
]

for title, body, label in issues:
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body + "\n\n> *This was generated by AI during triage.*",
        "--label", label
    ]
    try:
        subprocess.run(cmd, check=True)
        print(f"Created: {title}")
        time.sleep(1)
    except Exception as e:
        print(f"Failed: {title} - {e}")
