import subprocess
import os
import time

research_dirs = [
    "06_research/quantum",
    "06_research/quantum_os",
    "06_research/simulation",
    "06_research/optimization",
    "06_research/formal_methods",
    "06_research/decision_systems",
    "06_research/control_theory",
    "06_research/replay_math"
]

def create_research_issue(dir_path):
    module_name = os.path.basename(dir_path).replace('_', ' ').title()
    title = f"[RESEARCH-REVIEW] Review {module_name} module"
    
    body = f"""## Description
Review the research findings and implementation status of the `{module_name}` module.

## Metadata
- **Path:** `{dir_path}`
- **Category:** Research

## Analysis
Evaluate the relevance of this research to the PhoenixOS F1 maturity stage.

## Decision Matrix
- [ ] KEEP (Move to active development)
- [ ] EXPERIMENT (Keep in 06_research)
- [ ] REJECT (Move to 15_archive or 06_research/rejected)
- [ ] DEFER (Move to future roadmap)

> *This was generated by AI during triage.*
"""
    
    labels = "research-review,F0"
    if "quantum" in dir_path.lower():
        labels += ",quantum-review"
        
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body,
        "--label", labels
    ]
    
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"Created: {title}")
    except subprocess.CalledProcessError as e:
        print(f"Failed: {title} - {e.stderr}")

def main():
    for rd in research_dirs:
        if os.path.exists(rd):
            create_research_issue(rd)
            time.sleep(1)

if __name__ == "__main__":
    main()
