import subprocess
import csv
import time
import os

def create_issue(fileA, fileB, similarity):
    title = f"[DOCS-CLEANUP] Merge duplicate: {fileA} and {fileB}"
    
    # Extract purpose overlap (simple heuristic: common words in filename or first line)
    purpose = "Possible duplicate documentation files detected by similarity analysis."
    
    body = f"""## Description
High similarity detected between two documentation files.

## Metadata
- **File A:** `{fileA}`
- **File B:** `{fileB}`
- **Similarity Score:** `{similarity}`

## Analysis
- **Purpose Overlap:** {purpose}
- **Similarity %:** {float(similarity)*100:.1f}%
- **Merge Target:** TBD

## Risk Assessment
- Low: Documentation only.

## Decision Matrix
- [ ] MERGE
- [ ] ARCHIVE_LATER
- [ ] KEEP_SEPARATE
- [ ] DELETE_AFTER_VALIDATION

> *This was generated by AI during triage based on DOC_SIMILARITY_MATRIX.md.*
"""
    
    labels = "docs-cleanup,duplicate-doc,F0"
    
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body,
        "--label", labels
    ]
    
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"Created: {title}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"Failed: {title} - {e.stderr}")
        return False

def main():
    if not os.path.exists('DOC_SIMILARITY_MATRIX.md'):
        print("DOC_SIMILARITY_MATRIX.md not found. Run generate_similarity_matrix.py first.")
        return

    with open('DOC_SIMILARITY_MATRIX.md', 'r') as f:
        lines = f.readlines()

    # Skip header
    # | fileA | fileB | semantic_similarity | merge_candidate |
    # |---|---|---|---|
    matches = []
    for line in lines:
        if line.startswith('|') and 'fileA' not in line and '---' not in line:
            parts = [p.strip() for p in line.split('|') if p.strip()]
            if len(parts) >= 3:
                fileA = parts[0]
                fileB = parts[1]
                similarity = parts[2]
                matches.append((fileA, fileB, similarity))

    # Sort by similarity descending
    matches.sort(key=lambda x: x[2], reverse=True)

    # Limit to top N for safety/testing, or those with > 0.8 similarity
    target_matches = [m for m in matches if float(m[2]) >= 0.8]
    
    print(f"Found {len(target_matches)} high-similarity matches.")
    
    # Limit to 20 for this run to avoid spamming
    for i, (fileA, fileB, similarity) in enumerate(target_matches[:20]):
        if create_issue(fileA, fileB, similarity):
            time.sleep(1) # Be nice to API

if __name__ == "__main__":
    main()
