import subprocess
import time

root_cleanup_issues = [
    ("[CLEANUP] Review Phase Scripts in Root", "Multiple `phase_*.py` and `generate_phase_*.py` scripts are currently in the root directory.\n\nTasks:\n- Identify which scripts are still needed for F0/F1 maintenance.\n- Move necessary scripts to `05_tools/automation/`.\n- Archive or delete obsolete scripts.", "technical-debt,F0"),
    ("[CLEANUP] Relocate Large Index Files", "`FILE_INDEX.md` (38MB) and `PROJECT_TREE.txt` (28MB) are cluttering the root and slowing down git operations.\n\nTasks:\n- Move large indices to `00_program_management/reports/` or `.gitignore` them if regeneratable.\n- Update `README.md` and other docs to point to the new locations.", "technical-debt,F0"),
    ("[CLEANUP] Consolidate Audit Reports", "Multiple audit reports (`QUANTUM_AUDIT.md`, `TOPOLOGY_AUDIT.md`, `DOC_ANALYSIS.md`) are scattered in the root.\n\nTasks:\n- Move finalized reports to `02_docs/03_validation/`.\n- Update `DOC_INDEX.md` to reflect new paths.", "docs-cleanup,F0")
]

for title, body, label in root_cleanup_issues:
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body + "\n\n> *This was generated by AI during triage.*",
        "--label", label
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"Created: {title}")
        time.sleep(1)
    except subprocess.CalledProcessError as e:
        print(f"Failed: {title} - {e.stderr}")
