import subprocess
import time

imports = [
    ("openclaw", "03_repositories/forked/openclaw", "Personal AI Assistant base", "forked"),
    ("aegis-auth", "03_repositories/research/aegis-auth", "Authentication research", "research"),
    ("infrastructure", "03_repositories/research/infrastructure", "Infrastructure research", "research"),
    ("astraeus-core", "03_repositories/integrated/astraeus-core", "Engineering cognition system (L7)", "integrated"),
    ("gametrend-intelligence-engine", "03_repositories/experiments/gametrend-intelligence-engine", "Trend discovery research", "experiments"),
    ("cognitron-game", "03_repositories/experiments/cognitron-game", "Simulation/Game research", "experiments"),
    ("AutoMation-Engine", "03_repositories/research/AutoMation-Engine", "Task automation research", "research"),
    ("Noesis", "03_repositories/integrated/Noesis", "Autonomous research system (L5.5)", "integrated")
]

def create_import_issue(name, path, purpose, category):
    title = f"[IMPORT-REVIEW] Review {name} ({category})"
    
    body = f"""## Description
A new repository has been imported into the workspace and needs review.

## Metadata
- **Repository:** `{name}`
- **Path:** `{path}`
- **Purpose:** {purpose}
- **Category:** {category}

## Analysis
Evaluate how this repository aligns with the PhoenixOS roadmap and whether its components should be integrated into the core stack.

## Decision Matrix
- [ ] INTEGRATE (Move to phoenix_os/)
- [ ] KEEP (Leave in 03_repositories)
- [ ] ARCHIVE (Move to 15_archive)
- [ ] DELETE (Remove from workspace)

> *This was generated by AI during triage after new clones were detected.*
"""
    
    labels = "research-review,F0"
    if category == "integrated":
        labels += ",integration"
    elif category == "forked":
        labels += ",infrastructure"
        
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body,
        "--label", labels
    ]
    
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"Created: {title}")
        time.sleep(1)
    except subprocess.CalledProcessError as e:
        print(f"Failed: {title} - {e.stderr}")

if __name__ == "__main__":
    remaining = ["astraeus-core", "Noesis"]
    for name, path, purpose, category in imports:
        if name in remaining:
            create_import_issue(name, path, purpose, category)
