import subprocess
import time

tech_issues = [
    ("[DETERMINISM] Verify Kernel-level Determinism", "eBPF probes have not been evaluated under stress for deterministic behavior.\n\nTasks:\n- Implement stress tests for eBPF probes.\n- Verify logical clock consistency in kernel space.\n- Check for race conditions in shared memory buffers.", "determinism,replay-validation,F0"),
    ("[DETERMINISM] Distributed Consensus Validation", "Multi-node consensus tests have not been executed.\n\nTasks:\n- Set up multi-node test environment.\n- Verify PoA consensus convergence.\n- Test ledger synchronization across nodes.", "determinism,future-phase"),
    ("[RUNTIME] Warden State Oscillation Audit", "Audit the Warden FSM to ensure the DwellTicks hysteresis barrier prevents oscillations under jitter.\n\nTasks:\n- Run chaos tests with high event jitter.\n- Verify Warden state transition dwell times.\n- Check for edge cases in rollback triggers.", "runtime-validation,F0"),
    ("[SECURITY] Review Replay Attack Vectors", "The security tests in tests/security/replay_attack_test.go are currently minimal.\n\nTasks:\n- Implement robust replay attack scenarios.\n- Verify Ledger hash-chain rejection of duplicated event hashes.\n- Test TCS window evaluation under replay attempts.", "security-blocker,replay-validation,F0"),
    ("[TECH-DEBT] Unify 7-Layer Stack Imports", "Migrate all core imports to the new flat 'phoenix/layer' convention as per GITHUB_ISSUE_PLAN.md.\n\nTasks:\n- Update all files in phoenix_os/ to use new import style.\n- Remove go.work local replacement hacks.\n- Verify build and tests pass.", "technical-debt,F0"),
    ("[TECH-DEBT] Consolidate Research Subdirectories", "Clean up and consolidate subdirectories in 06_research/ based on the RESEARCH_INDEX.md.\n\nTasks:\n- Merge small research files into unified documents.\n- Archive rejected research modules.\n- Update RESEARCH_INDEX.md references.", "technical-debt,docs-cleanup,F0")
]

for title, body, label in tech_issues:
    cmd = [
        "gh", "issue", "create",
        "--title", title,
        "--body", body + "\n\n> *This was generated by AI during triage.*",
        "--label", label
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        print(f"Created: {title}")
        time.sleep(1)
    except subprocess.CalledProcessError as e:
        print(f"Failed: {title} - {e.stderr}")

if __name__ == "__main__":
    pass
